document.write('<header id="ABdev_main_header" class="header_layout_default clearfix" style="height:122px;">	');
document.write('        <div id="main_menu_container">	');
document.write('            <div class="container menu_container">	');
document.write('                <div class="row">	');
document.write('                    <div class="span5 first_menu">	');
document.write('                        <nav>	');
document.write('                            <ul id="main_menu_left" >	');
document.write('                                <li class="menu-item" style="padding:0;padding-top:35px;margin:0;margin-left:15px;"><a href="' + varcocrootpath + 'index.html">HOME</a></li>	');
document.write('                                <li class="menu-item" style="padding:0;padding-top:35px;margin:0;margin-left:15px;"><a href="#">LEADERSHIP</a>	');
document.write('                                    <ul>	');
document.write('                                        <li><a href="' + varcocrootpath + 'elders.html">SHEPHERDS</a></li>	');
document.write('                                        <li><a href="' + varcocrootpath + 'deacons.html">DEACONS</a></li>	');
document.write('                                        <li><a href="' + varcocrootpath + 'ministers.html">MINISTERS</a></li>	');
document.write('                                        <li><a href="' + varcocrootpath + 'staff.html">STAFF</a></li>	');
document.write('                                    </ul>	');
document.write('                                </li>	');
document.write('                                <li class="menu-item" style="padding:0;padding-top:35px;margin:0;margin-left:15px;"><a href="' + varcocrootpath + 'livestreaming.html">LIVESTREAM</a></li>	');
document.write('                            </ul>	');
document.write('                        </nav>	');
document.write('                    </div>	');
document.write('                            <div class="span2 tcvpb-centered">	');
document.write('                                <div id="logo">	');
document.write('                                        <img id="main_logo" src="' + varcocrootpath + 'images/logo.png" alt="Webb Chapel church of Christ" style="display:none; width:175px; height:auto !important; max-height:130px !important;">	');
document.write('                                        <img id="inverted_logo" class="hide" src="' + varcocrootpath + 'images/logo.png" alt="Webb Chapel church of Christ" style="width:175px;height:auto !important;">	');
document.write('                                        <img id="retina_logo" src="' + varcocrootpath + 'images/logo.png" alt="Webb Chahpel church of Christ" style="display:none; width:175px; height:auto !important; max-height:130px !important;">	');
document.write('                                        <img id="inverted_retina_logo" src="' + varcocrootpath + 'images/logo.png" alt="Webb Chapel church of Christ" style="display:none; width:175px; height:auto !important; max-height:130px !important;">	');
document.write('                                    </a>	');
document.write('                                </div>	');
document.write('                            </div>	');
document.write('                            <div class="span5 second_menu">	');
document.write('                                <nav>	');
document.write('                                    <ul id="main_menu_right" class="">	');
document.write('                                        <li class="menu-item" style="padding:0;padding-top:35px;margin:0;margin-left:15px;"><a href="' + varcocrootpath + 'smallgroups.html">SMALL GROUPS</a></li>	');
document.write('                                	<li class="menu-item" style="padding:0;padding-top:35px;margin:0;margin-left:15px;"><a href="#">MEMBERS</a>	');
document.write('                                    		<ul>	');
document.write('                                        		<li><a href="' + varcocrootpath + 'calendar.html">CALENDAR</a></li>	');
document.write('                                        		<li><a href="' + varcocrootpath + 'giving.html">GIVING</a></li>	');
document.write('                                        		<li><a href="https://onrealm.org/WebbChapelChurch" target="_blank">REALM LOGIN</a></li>	');
document.write('                                    		</ul>	');
document.write('                                	</li>	');
document.write('                                        <li class="menu-item" style="padding:0;padding-top:35px;margin:0;margin-left:15px;"><a href="' + varcocrootpath + 'contact.html">CONTACT</a></li>	');
document.write('                                    </ul>	');
document.write('                                </nav>	');
document.write('                            </div>	');
document.write('                        </div>	');
document.write('                    <div class="header_sidebar_toggle">	');
document.write('                        <span></span>	');
document.write('                    </div>	');
document.write('                </div>	');
document.write('        </div>	');
document.write('</header>   	');
