<?php
$lan = array(
  'You do not have enough priviliges to view this page' => 'Nie posiadasz wystarczaj±cych uprawnieñ aby wy¶wietliæ t± stronê',
  'Add a user' => 'dodaj u¿ytkownika',
  'add user' => 'Dodaj u¿ytkownika',
  'Members of' => 'Cz³onkowie',
  'Tag all users in this page' => 'Zaznacz wszystkich u¿ytkowników na tej stronie',
  'back to this list' => 'powrót do listy',
  'Download users on this list as a CSV file' => 'Pobierz u¿ytkowników tej listy do pliku CSV',
  'Please enter a listid' => 'Wprowad¼ identyfikator listy',
  'Processing' => 'Przetwarzam',
  'users were moved to' => 'u¿ytkownicy zostali przeniesieni do',
  'users were copied to' => 'u¿ytkownicy zostali skopiowani do',
  'users were deleted from this list' => 'u¿ytkownicy zostali usuniêci z tej listy',
  'Users found, click add to add this user' => 'Znaleziono u¿ytkowników, kliknij Dodaj aby dodaæ u¿ytkownika',
  'Add' => 'Dodaj',
  'No user found with that email' => 'Nie znaleziono u¿ytkowników z tym adresem email',
  'Inserting user' => 'Wstawianie u¿ytkownika',
  'User added' => 'U¿ytkownik dodany',
  'Deleting' => 'Usuwanie',
  'Done' => 'Gotowe',
  'Users on this list' => 'U¿ytkowników na tej li¶cie',
  'Listing user' => 'Wy¶wietl u¿ytkownika',
  'to' => 'do',//in sentence 'listing user 1  to  50'
  'Listing user 1 to 50' => 'Wy¶wietl u¿ytkowników 1 do 50',
  'Members' => 'Cz³onkowie',
  'confirmed' => 'potwierdzony',
  'tag' => 'oznacz',
  'del' => 'usuñ',
  'Delete'=>'Usuñ',
  '# msgs' => '# wiad.',
  '# rss' => '# rss',
  'rss freq' => 'czêstotliwo¶æ rss',
  'last sent' => 'ostatnio wys³ano',
  'What to do with "Tagged" users' => 'Co zrobiæ z oznaczonymi u¿ytkownikami',
  'This will only process the users in this page that have the "Tag" checkbox checked' => 'Przetworzeni zostan± tylko u¿ytkownicy na tej stronie, którzy maj± zaznaczone pole "oznacz"',
  'delete' => 'Usuñ',
  'move' => 'Przenie¶',
  'copy' => 'Kopiuj',
  'nothing' => 'Nic',
  'to' => 'do', # as in destination
  'from this list' => 'z tej listy',
  'What to do with all users' => 'Co zrobiæ ze wszystkimi u¿ytkownikami',
  'This will process all users on this list' => 'Przetworzeni zostan± wszyscy u¿ytkownicy z listy',
  'do it' => 'wykonaj',
  
  
);
?>