<?php

$lan = array(
'Running in testmode, no emails will be sent. Check your config file.' => 'uruchomiono w trybie testowym. Wiadomo¶ci nie bêd± wysy³ane. Sprawd¼ plik konfiguracyjny.',
'The following restrictions have been set by your ISP:' => 'Nastêpuj±ce ograniczenia zosta³u ustawione przez Twojego dostawcê Internetu:',
'Script stage' => 'Etap skryptu',
'Finished, Nothing to do' => 'Ukoñczono, nie ma nic do zrobienia',
'messages sent in' => 'wiadomo¶ci wys³ano w',
'seconds' => 'sekund',
'invalid emails' => 'nieprawid³owych adresów email',
'emails failed (will retry later)' => 'adresów, na które nie mozna by³o wys³aæ (próba zostanie powtórzona pó¼niej)',
'emails unconfirmed (not sent)' => 'niepotwierdzonych adresów email (nie wys³ano)',
'Warning: script never reached stage 5' => 'Uwaga: skrypt nie osi±gn±³ etapu 5',
'This may be caused by a too slow or too busy server' => 'Mo¿e to byæ spowodowane przez zbyt wolny lub zbyt zajêty serwer',


'In safe mode, batches are set to a maximum of 100' => 'W trybie awaryjnym, partie s± ustawione maksymalnie na 100',
'Running in safe mode' => 'uruchomiono w trybie awaryjnym',
'msgs/hr' => 'wiad/godz.',
'Reload required' => 'Konieczne prze³adowanie',
'Finished, All done' => 'Ukoñczono, Wszystko zrobione.',
'Script finished, but not all messages have been sent yet.' => 'Skrypt ukoñczony ale nie wszystkie wiadomo¶ci zosta³y jeszscze wys³ane.',
'Finished this run' => 'Zakoñczono to uruchomienie',
'(test)' => '(test)',
'Would have sent' => 'Zosta³oby wys³ane',
'(test)' => '(test)',
'Would have sent' => 'Zosta³oby wys³ane',
'Started' => 'Uruchomiono',
'Processing has been suspended by your ISP, please try again later' => 'Przetwarzanie zosta³o wstrzymane przez dostawê Internetu, spróbuj pó¼niej',
'Sending in batches of' => 'Wysy³anie w partiach ',
'emails' => 'emaili',
'This batch will be' => 'W tej partii bêdzie',
'emails, because in the last' => 'emaili, poniewa¿ jest ostatnia',
'emails were sent' => 'emaili wys³ano',
'Sending in batches of' => 'Wysy³anie w partiach ',
'emails' => 'emaili',
'In the last' => 'W ostatnich',
'seconds more emails were sent' => 'sekundach zosta³o wys³anych wiêcej emaili',
'than is currently allowed per batch' => 'ni¿ jest to obecnie dozwolone w partii',
'Sent in last run' => 'Wys³ano w ostatnim uruchomieniu',
'Skipped in last run' => 'Pominiêto w ostatnim uruchomieniu',
'Processing has started,' => 'Uruchomiono przetwarzanie,',
'message(s) to process.' => 'wiadomo¶ci do przetworzenia.',
'It is safe to click your stop button now, report will be sent by email to' => 'Teraz mo¿esz klikn±æ przycisk "stop", raport zostanie wys³any poczt± na adres',
'Your webserver is running in safe_mode. Please keep this window open. It may reload several times to make sure all messages are sent.' => 'Twój serwer WWW jest uruchomiony w trybie awaryjnym. Zostaw to okno otwarte. Mo¿e ono prze³adowywaæ siê kilka razy aby uby³a pewno¶æ, ¿e wszystkie wiadomo¶ci zosta³y wys³ane.',
'Reports will be sent by email to' => 'Raport zostanie wys³any poczt± na adres',
'Processing message' => 'Przetwarzanie wiadomo¶ci nr',
'Message' => 'Wiadomo¶æ',
'is an RSS feed for' => 'jest nag³ówkiem RSS dla',
'Looking for users' => 'Wyszukiwanie u¿ytkowników',
'users apply for attributes, now checking lists' => 'wybrane atrybuty u¿ytkownika s± odpowiednie, sprawdzanie list',
'No users apply for attributes' => '¯aden u¿ytkownik nie pasuje do wybranych atrybutów',
'looking for users who can be excluded from this mailing' => 'Poszukiwanie u¿ytkowników, którzy mog± zostaæ wy³±czeni z tego przetwarzania',
'Process Killed by other process' => 'Proces zosta³ zakoñczony przez inny proces',
'Found them' => 'Znaleziono',
'to process' => 'do przetworzenia',
'No users to process for this batch' => 'Brak u¿ytkowników do przetworzenia w tej partii',
'batch limit reached' => 'osi±gniêto limit partii',
'Process Killed by other process' => 'Proces zosta³ zakoñczony przez inny proces',
'Message I was working on has disappeared' => 'Przetwarzana wiadomo¶æ zniknê³a',
'Sending' => 'Wysy³anie',
'It took' => 'Minê³o',
'seconds to send' => 'sekund podczas wysy³ania',
'Failed sending to' => 'Nie powiod³o siê wysy³anie do',
'Unconfirmed user' => 'U¿ytkownik niepotwierdzony',
'Not sending to' => 'Nie wys³ano do',
'already sent' => 'wys³ano',
'Processed' => 'Przetworzono',
'out of' => 'z',
'Hmmm, No users found to send to' => 'Hmmm, nie znaleziono u¿ytkowników aby wys³aæ',
'It took' => 'Minê³o',
'to send this message' => 'podczas wysy³ania tej wiadomo¶ci',
'waiting for' => 'oczekiwanie na',
'to make sure we don\'t exceed our limit of' => 'aby byæ pewnym, ¿e nie przekroczymy limitu',
'messages in' => 'wiadomo¶ci w',

### new in 2.9.5
'Message Sending has started' => 'Rozsy³anie wiadomo¶ci rozpoczête',
'phplist has started sending the message with subject %s' => 'phplist - rozpoczêto rozsy³anie wiadomo¶ci o temacie %s',
'to view the progress of this message, go to %s' => 'aby obejrzeæ postêp wysy³ania kliknij %s',
'There have been more than 10 attempts to send to %s that have been blocked for domain throttling.' => 'Ponad 10 razy próbowano wys³aæ do %s. Próby te zosta³y zablokowane poprzez przepustowo¶æ domeny.',
'Introducing extra delay to decrease throttle failures' => 'Wprowadzanie dodatkowego opó¼nienia aby obni¿yæ b³êdy przepustowo¶ci',
'%s is currently over throttle limit of %d per %d seconds' => '%s jest aktualnie ponad limit przepustowo¶ci %d na %d sekund',
'not sending to ' => 'nie wysy³am do ',
'Message Sending has finished' => 'Ukoñczono wysy³anie wiadomo¶ci',
'phplist has finished sending the message with subject %s' => 'phplist - zakoñczono wysy³anie wiadomo¶ci o temacie %s',

'Sending of this message has been suspended' => 'Wysy³anie tej wiadomo¶ci zosta³o wstrzymane',

# new in 2.10.1
'Less than batch size were sent, so reloading imminently' => 'Wys³ano mniej niz w partii, wiêc prze³adowuje natychmiast',
'Waiting for %d seconds before reloading' => 'oczekiwanie %d sekund przed prze³adowaniem',
'Please leave this window open. You have batch processing enabled, so it will reload several times to send the messages. Reports will be sent by email to' => 'Pozostaw to okno otwarte. Rozpocz±³e¶ przetwarzanie partii, wiêc okno bêdzie siê prze³adowywa³o kilka razy aby wys³aæ wiadomo¶ci. Raport zostanie wys³any poczt± na adres',

);

?>