<?php
if (!defined("PJ_HOST")) define("PJ_HOST", "localhost");
if (!defined("PJ_USER")) define("PJ_USER", "webbchap_caladm2");
if (!defined("PJ_PASS")) define("PJ_PASS", "webbchap777!");
if (!defined("PJ_DB")) define("PJ_DB", "webbchap_calendar2");
if (!defined("PJ_PREFIX")) define("PJ_PREFIX", "");
if (!defined("PJ_INSTALL_FOLDER")) define("PJ_INSTALL_FOLDER", "/calendar2/");
if (!defined("PJ_INSTALL_PATH")) define("PJ_INSTALL_PATH", "/home/webbchap/public_html/calendar2/");
if (!defined("PJ_INSTALL_URL")) define("PJ_INSTALL_URL", "https://www.webbchapel.org/calendar2/");
if (!defined("PJ_SALT")) define("PJ_SALT", "ON4FRN2V");
if (!defined("PJ_INSTALLATION")) define("PJ_INSTALLATION", "MTIyMjI1MjEwMjQ2NDM0NzgxMDU1MDg4NjgzNTgxNTA4NzM0MzQ1ODYzNDg0OTgyMDMwNTk0MDgxMzkwNTAxODk3NzYwMjUxNjIxNTQxMTM5MTk0ODU5MjczMTM3NTM2ODcwMSAyMjQ2MDc3OTQ2NjQwNjE1NzA3ODc1MTQ3Mjk0NjMwOTc1ODI1Mzg3Mjg4MzU4NzgwMjA3NDEzMjkxOTIzMTY1NTUzNTAzMzQxNjMwMjQ5OTk3NTk1NTYzMDM1NzQ5MTg0OTggNTM3ODM0OTIxOTkwMjIwODE0MDc2NDUxNjEwMDEwNjkyMzY3MDM5MzA1NjY1MjE0MjE2MDY1ODU3NDYzODI5NzUyODkxMjI0NTMxNTAwNzk4Njc3NjcwMjQ4NDc2NDY1NDU2IDE1ODkzODQzMjYyOTU2MTYyMzk3MzExNzAzMTk5NjU2NDg4NTU2OTA1ODcwNTI4MzAxNzI5MDIyNTUzMjA4MDU2ODM3MjkyMjQ1NzYwMzIxNDg5MjQ5ODI5NzI0MTcwMjc5IDExNDEzOTc4MDgzNDU4NDE3NTQ0OTA0ODY2MjY5Nzg4ODMzNjQ0NzY5ODQ2MDY3OTcyMzY3ODcyMDQ4MTI0NjgxMzU1MzI2OTc2NDA1ODY4Mzk0OTQwMDU0Njc1MDk3NjQ1NTcgODMyNTc3MTg3NTQ0MTkxNzU5MTcwOTY2NDU2MzI2NDkwOTA4OTc0ODMxODg5MzQ1NDQ3NzY4MjM5OTc1NDk1MzM4OTI5MDgyNDAyOTgwMTQyNjQ5MjM4Mzg1NTg1NTk5NzI3");
?>