DROP TABLE IF EXISTS `phpeventcalendar_fields`;
CREATE TABLE IF NOT EXISTS `phpeventcalendar_fields` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `key` varchar(255) DEFAULT NULL,
  `type` enum('backend','frontend','arrays') DEFAULT NULL,
  `label` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `key` (`key`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `phpeventcalendar_multi_lang`;
CREATE TABLE IF NOT EXISTS `phpeventcalendar_multi_lang` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `foreign_id` int(10) unsigned DEFAULT NULL,
  `model` varchar(100) DEFAULT NULL,
  `locale` tinyint(3) unsigned DEFAULT NULL,
  `field` varchar(100) DEFAULT NULL,
  `content` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `foreign_id` (`foreign_id`,`model`,`locale`,`field`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `phpeventcalendar_options`;
CREATE TABLE IF NOT EXISTS `phpeventcalendar_options` (
  `foreign_id` int(10) unsigned NOT NULL DEFAULT '0',
  `key` varchar(255) NOT NULL DEFAULT '',
  `tab_id` tinyint(3) unsigned DEFAULT NULL,
  `value` text,
  `label` text,
  `type` enum('string','text','int','float','enum') NOT NULL DEFAULT 'string',
  `order` int(10) unsigned DEFAULT NULL,
  `is_visible` tinyint(1) unsigned DEFAULT '1',
  `style` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`foreign_id`,`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `phpeventcalendar_roles`;
CREATE TABLE IF NOT EXISTS `phpeventcalendar_roles` (
  `id` tinyint(3) unsigned NOT NULL AUTO_INCREMENT,
  `role` varchar(255) DEFAULT NULL,
  `status` enum('T','F') NOT NULL DEFAULT 'T',
  PRIMARY KEY (`id`),
  KEY `status` (`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `phpeventcalendar_users`;
CREATE TABLE IF NOT EXISTS `phpeventcalendar_users` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `role_id` int(10) unsigned NOT NULL,
  `email` varchar(255) default NULL,
  `password` blob,
  `name` varchar(255) default NULL,
  `phone` varchar(255) DEFAULT NULL,
  `created` datetime NOT NULL,
  `last_login` datetime default NULL,
  `status` enum('T','F') NOT NULL default 'T',
  `is_active` enum('T','F') NOT NULL default 'F',
  `ip` varchar(15) default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `email` (`email`),
  KEY `role_id` (`role_id`),
  KEY `status` (`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `phpeventcalendar_categories`;
CREATE TABLE IF NOT EXISTS `phpeventcalendar_categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT, 
  `category` varchar(255) default NULL,
  `status` enum('T','F') NOT NULL DEFAULT 'T',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `phpeventcalendar_events`;
CREATE TABLE IF NOT EXISTS `phpeventcalendar_events` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT, 
  `recurring_id` varchar(255) default NULL,
  `category_id` int(11) default NULL,
  `event_title` varchar(255) default NULL,
  `description` text default NULL,
  `event_date` date default NULL,
  `start_time` time default NULL,
  `end_time` time default NULL,
  `status` enum('T','F') NOT NULL DEFAULT 'T',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

INSERT INTO `phpeventcalendar_fields` (`id`, `key`, `type`, `label`) VALUES
(1, 'addLocale', 'backend', 'Add language'),
(2, 'adminForgot', 'backend', 'Forgot password'),
(3, 'adminLogin', 'backend', 'Admin Login'),
(4, 'backend', 'backend', 'Backend titles'),
(5, 'btnAdd', 'backend', 'Button Add'),
(6, 'btnBack', 'backend', 'Button Back'),
(7, 'btnBackup', 'backend', 'Button Backup'),
(8, 'btnCancel', 'backend', 'Button Cancel'),
(9, 'btnContinue', 'backend', 'Button Continue'),
(10, 'btnDelete', 'backend', 'Button Delete'),
(11, 'btnLogin', 'backend', 'Login'),
(12, 'btnReset', 'backend', 'Reset'),
(13, 'btnSave', 'backend', 'Save'),
(14, 'btnSearch', 'backend', 'Search'),
(15, 'btnSend', 'backend', 'Button Send'),
(16, 'btnUpdate', 'backend', 'Update'),
(17, 'created', 'backend', 'Created'),
(18, 'email', 'backend', 'E-Mail'),
(19, 'emailForgotBody', 'backend', 'Email / Forgot Body'),
(20, 'emailForgotSubject', 'backend', 'Email / Forgot Subject'),
(21, 'frontend', 'backend', 'Front-end titles'),
(22, 'gridActionTitle', 'backend', 'Grid / Action Title'),
(23, 'gridBtnCancel', 'backend', 'Grid / Button Cancel'),
(24, 'gridBtnDelete', 'backend', 'Grid / Button Delete'),
(25, 'gridBtnOk', 'backend', 'Grid / Button OK'),
(26, 'gridChooseAction', 'backend', 'Grid / Choose Action'),
(27, 'gridConfirmationTitle', 'backend', 'Grid / Confirmation Title'),
(28, 'gridDeleteConfirmation', 'backend', 'Grid / Delete confirmation'),
(29, 'gridEmptyResult', 'backend', 'Grid / Empty resultset'),
(30, 'gridGotoPage', 'backend', 'Grid / Go to page'),
(31, 'gridItemsPerPage', 'backend', 'Grid / Items per page'),
(32, 'gridNext', 'backend', 'Grid / Next'),
(33, 'gridNextPage', 'backend', 'Grid / Next page'),
(34, 'gridPrev', 'backend', 'Grid / Prev'),
(35, 'gridPrevPage', 'backend', 'Grid / Prev page'),
(36, 'gridTotalItems', 'backend', 'Grid / Total items'),
(37, 'infoListingAddressBody', 'backend', 'Infobox / Listing Address Body'),
(38, 'infoListingAddressTitle', 'backend', 'Infobox / Listing Address Title'),
(39, 'infoListingBookingsBody', 'backend', 'Infobox / Listing Bookings Body'),
(40, 'infoListingBookingsTitle', 'backend', 'Infobox / Listing Bookings Title'),
(41, 'infoListingContactBody', 'backend', 'Infobox / Listing Contact Body'),
(42, 'infoListingContactTitle', 'backend', 'Infobox / Listing Contact Title'),
(43, 'infoListingExtendBody', 'backend', 'Infobox / Extend exp.date Body'),
(44, 'infoListingExtendTitle', 'backend', 'Infobox / Extend exp.date Title'),
(45, 'infoListingPricesBody', 'backend', 'Infobox / Listing Prices Body'),
(46, 'infoListingPricesTitle', 'backend', 'Infobox / Listing Prices Title'),
(47, 'infoLocalesArraysBody', 'backend', 'Locale / Languages Array Body'),
(48, 'infoLocalesArraysTitle', 'backend', 'Locale / Languages Array Title'),
(49, 'infoLocalesBackendBody', 'backend', 'Infobox / Locales Backend Body'),
(50, 'infoLocalesBackendTitle', 'backend', 'Infobox / Locales Backend Title'),
(51, 'infoLocalesBody', 'backend', 'Infobox / Locales Body'),
(52, 'infoLocalesFrontendBody', 'backend', 'Infobox / Locales Frontend Body'),
(53, 'infoLocalesFrontendTitle', 'backend', 'Infobox / Locales Frontend Title'),
(54, 'infoLocalesTitle', 'backend', 'Infobox / Locales Title'),
(55, 'lblAddUser', 'backend', 'Add user'),
(56, 'lblBackupDatabase', 'backend', 'Backup / Database'),
(57, 'lblBackupFiles', 'backend', 'Backup / Files'),
(58, 'lblChoose', 'backend', 'Choose'),
(59, 'lblDays', 'backend', 'Days'),
(60, 'lblDelete', 'backend', 'Delete'),
(61, 'lblError', 'backend', 'Error'),
(62, 'lblExport', 'backend', 'Export'),
(63, 'lblForgot', 'backend', 'Forgot password'),
(64, 'lblIp', 'backend', 'IP address'),
(65, 'lblIsActive', 'backend', 'Is Active'),
(66, 'lblName', 'backend', 'Name'),
(67, 'lblNo', 'backend', 'No'),
(68, 'lblOption', 'backend', 'Option'),
(69, 'lblOptionList', 'backend', 'Option list'),
(70, 'lblRole', 'backend', 'Role'),
(71, 'lblStatus', 'backend', 'Status'),
(72, 'lblType', 'backend', 'Type'),
(73, 'lblUpdateUser', 'backend', 'Update user'),
(74, 'lblUserCreated', 'backend', 'User / Registration Date & Time'),
(75, 'lblValue', 'backend', 'Value'),
(76, 'lblYes', 'backend', 'Yes'),
(77, 'lnkBack', 'backend', 'Link Back'),
(78, 'localeArrays', 'backend', 'Locale / Arrays titles'),
(79, 'locales', 'backend', 'Languages'),
(80, 'locale_flag', 'backend', 'Locale / Flag'),
(81, 'locale_is_default', 'backend', 'Locale / Is default'),
(82, 'locale_order', 'backend', 'Locale / Order'),
(83, 'locale_title', 'backend', 'Locale / Title'),
(84, 'menuBackup', 'backend', 'Menu Backup'),
(85, 'menuDashboard', 'backend', 'Menu Dashboard'),
(86, 'menuLang', 'backend', 'Menu Multi lang'),
(87, 'menuLocales', 'backend', 'Menu Languages'),
(88, 'menuLogout', 'backend', 'Menu Logout'),
(89, 'menuOptions', 'backend', 'Menu Options'),
(90, 'menuPlugins', 'backend', 'Menu Plugins'),
(91, 'menuProfile', 'backend', 'Menu Profile'),
(92, 'menuUsers', 'backend', 'Menu Users'),
(93, 'multilangTooltip', 'backend', 'MultiLang / Tooltip'),
(94, 'opt_o_currency', 'backend', 'Options / Currency'),
(95, 'opt_o_date_format', 'backend', 'Options / Date format'),
(96, 'opt_o_timezone', 'backend', 'Options / Timezone'),
(97, 'opt_o_week_start', 'backend', 'Options / First day of the week'),
(98, 'pass', 'backend', 'Password'),
(99, 'pec_active', 'backend', 'Active'),
(100, 'pec_delete_selected', 'backend', 'Delete selected'),
(101, 'pec_email_taken', 'backend', 'Users / Email already taken'),
(102, 'pec_inactive', 'backend', 'Inactive'),
(103, 'plugin_locale_add_lang', 'backend', 'Locale plugin / Add Language'),
(104, 'plugin_locale_index_body', 'backend', 'Locale plugin / Languages info body'),
(105, 'plugin_locale_index_title', 'backend', 'Locale plugin / Languages info title'),
(106, 'plugin_locale_languages', 'backend', 'Locale plugin / Languages'),
(107, 'plugin_locale_lbl_field', 'backend', 'Locale plugin / Field'),
(108, 'plugin_locale_lbl_flag', 'backend', 'Locale plugin / Flag'),
(109, 'plugin_locale_lbl_is_default', 'backend', 'Locale plugin / Is default'),
(110, 'plugin_locale_lbl_order', 'backend', 'Locale plugin / Order'),
(111, 'plugin_locale_lbl_title', 'backend', 'Locale plugin / Title'),
(112, 'plugin_locale_lbl_type', 'backend', 'Locale plugin / Type'),
(113, 'plugin_locale_lbl_value', 'backend', 'Locale plugin / Value'),
(114, 'plugin_locale_titles', 'backend', 'Locale plugin / Titles'),
(115, 'plugin_locale_titles_body', 'backend', 'Locale plugin / Titles info body'),
(116, 'plugin_locale_titles_title', 'backend', 'Locale plugin / Titles info title'),
(117, 'plugin_locale_type_arrays', 'backend', 'Locale plugin / Special title'),
(118, 'plugin_locale_type_backend', 'backend', 'Locale plugin / Back-end title'),
(119, 'plugin_locale_type_frontend', 'backend', 'Locale plugin / Front-end title'),
(120, 'plugin_log_btn_empty', 'backend', 'Log plugin / Empty button'),
(121, 'plugin_log_menu_config', 'backend', 'Log plugin / Menu Config'),
(122, 'plugin_log_menu_log', 'backend', 'Log plugin / Menu Log'),
(123, 'revert_status', 'backend', 'Revert status'),
(124, 'url', 'backend', 'URL'),
(125, 'user', 'backend', 'Username'),
(126, 'days_ARRAY_0', 'arrays', 'days_ARRAY_0'),
(127, 'days_ARRAY_1', 'arrays', 'days_ARRAY_1'),
(128, 'days_ARRAY_2', 'arrays', 'days_ARRAY_2'),
(129, 'days_ARRAY_3', 'arrays', 'days_ARRAY_3'),
(130, 'days_ARRAY_4', 'arrays', 'days_ARRAY_4'),
(131, 'days_ARRAY_5', 'arrays', 'days_ARRAY_5'),
(132, 'days_ARRAY_6', 'arrays', 'days_ARRAY_6'),
(133, 'day_names_ARRAY_0', 'arrays', 'day_names_ARRAY_0'),
(134, 'day_names_ARRAY_1', 'arrays', 'day_names_ARRAY_1'),
(135, 'day_names_ARRAY_2', 'arrays', 'day_names_ARRAY_2'),
(136, 'day_names_ARRAY_3', 'arrays', 'day_names_ARRAY_3'),
(137, 'day_names_ARRAY_4', 'arrays', 'day_names_ARRAY_4'),
(138, 'day_names_ARRAY_5', 'arrays', 'day_names_ARRAY_5'),
(139, 'day_names_ARRAY_6', 'arrays', 'day_names_ARRAY_6'),
(140, 'error_bodies_ARRAY_AA10', 'arrays', 'error_bodies_ARRAY_AA10'),
(141, 'error_bodies_ARRAY_AA11', 'arrays', 'error_bodies_ARRAY_AA11'),
(142, 'error_bodies_ARRAY_AA12', 'arrays', 'error_bodies_ARRAY_AA12'),
(143, 'error_bodies_ARRAY_AA13', 'arrays', 'error_bodies_ARRAY_AA13'),
(144, 'error_bodies_ARRAY_AB01', 'arrays', 'error_bodies_ARRAY_AB01'),
(145, 'error_bodies_ARRAY_AB02', 'arrays', 'error_bodies_ARRAY_AB02'),
(146, 'error_bodies_ARRAY_AB03', 'arrays', 'error_bodies_ARRAY_AB03'),
(147, 'error_bodies_ARRAY_AB04', 'arrays', 'error_bodies_ARRAY_AB04'),
(148, 'error_bodies_ARRAY_ALC01', 'arrays', 'error_bodies_ARRAY_ALC01'),
(149, 'error_bodies_ARRAY_AO01', 'arrays', 'error_bodies_ARRAY_AO01'),
(150, 'error_bodies_ARRAY_AU01', 'arrays', 'error_bodies_ARRAY_AU01'),
(151, 'error_bodies_ARRAY_AU03', 'arrays', 'error_bodies_ARRAY_AU03'),
(152, 'error_bodies_ARRAY_AU04', 'arrays', 'error_bodies_ARRAY_AU04'),
(153, 'error_bodies_ARRAY_AU08', 'arrays', 'error_bodies_ARRAY_AU08'),
(154, 'error_bodies_ARRAY_PAL01', 'arrays', 'Locale plugin / Status body'),
(155, 'error_bodies_ARRAY_PLG01', 'arrays', 'error_bodies_ARRAY_PLG01'),
(156, 'error_titles_ARRAY_AA10', 'arrays', 'error_titles_ARRAY_AA10'),
(157, 'error_titles_ARRAY_AA11', 'arrays', 'error_titles_ARRAY_AA11'),
(158, 'error_titles_ARRAY_AA12', 'arrays', 'error_titles_ARRAY_AA12'),
(159, 'error_titles_ARRAY_AA13', 'arrays', 'error_titles_ARRAY_AA13'),
(160, 'error_titles_ARRAY_AB01', 'arrays', 'error_titles_ARRAY_AB01'),
(161, 'error_titles_ARRAY_AB02', 'arrays', 'error_titles_ARRAY_AB02'),
(162, 'error_titles_ARRAY_AB03', 'arrays', 'error_titles_ARRAY_AB03'),
(163, 'error_titles_ARRAY_AB04', 'arrays', 'error_titles_ARRAY_AB04'),
(164, 'error_titles_ARRAY_AO01', 'arrays', 'error_titles_ARRAY_AO01'),
(165, 'error_titles_ARRAY_AU01', 'arrays', 'error_titles_ARRAY_AU01'),
(166, 'error_titles_ARRAY_AU03', 'arrays', 'error_titles_ARRAY_AU03'),
(167, 'error_titles_ARRAY_AU04', 'arrays', 'error_titles_ARRAY_AU04'),
(168, 'error_titles_ARRAY_AU08', 'arrays', 'error_titles_ARRAY_AU08'),
(169, 'error_titles_ARRAY_PAL01', 'arrays', 'Locale plugin / Status title'),
(170, 'error_titles_ARRAY_PLG01', 'arrays', 'error_titles_ARRAY_PLG01'),
(171, 'filter_ARRAY_active', 'arrays', 'filter_ARRAY_active'),
(172, 'filter_ARRAY_inactive', 'arrays', 'filter_ARRAY_inactive'),
(173, 'login_err_ARRAY_1', 'arrays', 'login_err_ARRAY_1'),
(174, 'login_err_ARRAY_2', 'arrays', 'login_err_ARRAY_2'),
(175, 'login_err_ARRAY_3', 'arrays', 'login_err_ARRAY_3'),
(176, 'months_ARRAY_1', 'arrays', 'months_ARRAY_1'),
(177, 'months_ARRAY_10', 'arrays', 'months_ARRAY_10'),
(178, 'months_ARRAY_11', 'arrays', 'months_ARRAY_11'),
(179, 'months_ARRAY_12', 'arrays', 'months_ARRAY_12'),
(180, 'months_ARRAY_2', 'arrays', 'months_ARRAY_2'),
(181, 'months_ARRAY_3', 'arrays', 'months_ARRAY_3'),
(182, 'months_ARRAY_4', 'arrays', 'months_ARRAY_4'),
(183, 'months_ARRAY_5', 'arrays', 'months_ARRAY_5'),
(184, 'months_ARRAY_6', 'arrays', 'months_ARRAY_6'),
(185, 'months_ARRAY_7', 'arrays', 'months_ARRAY_7'),
(186, 'months_ARRAY_8', 'arrays', 'months_ARRAY_8'),
(187, 'months_ARRAY_9', 'arrays', 'months_ARRAY_9'),
(188, 'personal_titles_ARRAY_dr', 'arrays', 'personal_titles_ARRAY_dr'),
(189, 'personal_titles_ARRAY_miss', 'arrays', 'personal_titles_ARRAY_miss'),
(190, 'personal_titles_ARRAY_mr', 'arrays', 'personal_titles_ARRAY_mr'),
(191, 'personal_titles_ARRAY_mrs', 'arrays', 'personal_titles_ARRAY_mrs'),
(192, 'personal_titles_ARRAY_ms', 'arrays', 'personal_titles_ARRAY_ms'),
(193, 'personal_titles_ARRAY_other', 'arrays', 'personal_titles_ARRAY_other'),
(194, 'personal_titles_ARRAY_prof', 'arrays', 'personal_titles_ARRAY_prof'),
(195, 'personal_titles_ARRAY_rev', 'arrays', 'personal_titles_ARRAY_rev'),
(196, 'short_months_ARRAY_1', 'arrays', 'short_months_ARRAY_1'),
(197, 'short_months_ARRAY_10', 'arrays', 'short_months_ARRAY_10'),
(198, 'short_months_ARRAY_11', 'arrays', 'short_months_ARRAY_11'),
(199, 'short_months_ARRAY_12', 'arrays', 'short_months_ARRAY_12'),
(200, 'short_months_ARRAY_2', 'arrays', 'short_months_ARRAY_2'),
(201, 'short_months_ARRAY_3', 'arrays', 'short_months_ARRAY_3'),
(202, 'short_months_ARRAY_4', 'arrays', 'short_months_ARRAY_4'),
(203, 'short_months_ARRAY_5', 'arrays', 'short_months_ARRAY_5'),
(204, 'short_months_ARRAY_6', 'arrays', 'short_months_ARRAY_6'),
(205, 'short_months_ARRAY_7', 'arrays', 'short_months_ARRAY_7'),
(206, 'short_months_ARRAY_8', 'arrays', 'short_months_ARRAY_8'),
(207, 'short_months_ARRAY_9', 'arrays', 'short_months_ARRAY_9'),
(208, 'status_ARRAY_1', 'arrays', 'status_ARRAY_1'),
(209, 'status_ARRAY_123', 'arrays', 'status_ARRAY_123'),
(210, 'status_ARRAY_2', 'arrays', 'status_ARRAY_2'),
(211, 'status_ARRAY_3', 'arrays', 'status_ARRAY_3'),
(212, 'status_ARRAY_7', 'arrays', 'status_ARRAY_7'),
(213, 'status_ARRAY_996', 'arrays', 'status_ARRAY_996'),
(214, 'status_ARRAY_997', 'arrays', 'status_ARRAY_997'),
(215, 'status_ARRAY_998', 'arrays', 'status_ARRAY_998'),
(216, 'status_ARRAY_999', 'arrays', 'status_ARRAY_999'),
(217, 'status_ARRAY_9997', 'arrays', 'status_ARRAY_9997'),
(218, 'status_ARRAY_9998', 'arrays', 'status_ARRAY_9998'),
(219, 'status_ARRAY_9999', 'arrays', 'status_ARRAY_9999'),
(220, 'timezones_ARRAY_-10800', 'arrays', 'timezones_ARRAY_-10800'),
(221, 'timezones_ARRAY_-14400', 'arrays', 'timezones_ARRAY_-14400'),
(222, 'timezones_ARRAY_-18000', 'arrays', 'timezones_ARRAY_-18000'),
(223, 'timezones_ARRAY_-21600', 'arrays', 'timezones_ARRAY_-21600'),
(224, 'timezones_ARRAY_-25200', 'arrays', 'timezones_ARRAY_-25200'),
(225, 'timezones_ARRAY_-28800', 'arrays', 'timezones_ARRAY_-28800'),
(226, 'timezones_ARRAY_-32400', 'arrays', 'timezones_ARRAY_-32400'),
(227, 'timezones_ARRAY_-3600', 'arrays', 'timezones_ARRAY_-3600'),
(228, 'timezones_ARRAY_-36000', 'arrays', 'timezones_ARRAY_-36000'),
(229, 'timezones_ARRAY_-39600', 'arrays', 'timezones_ARRAY_-39600'),
(230, 'timezones_ARRAY_-43200', 'arrays', 'timezones_ARRAY_-43200'),
(231, 'timezones_ARRAY_-7200', 'arrays', 'timezones_ARRAY_-7200'),
(232, 'timezones_ARRAY_0', 'arrays', 'timezones_ARRAY_0'),
(233, 'timezones_ARRAY_10800', 'arrays', 'timezones_ARRAY_10800'),
(234, 'timezones_ARRAY_14400', 'arrays', 'timezones_ARRAY_14400'),
(235, 'timezones_ARRAY_18000', 'arrays', 'timezones_ARRAY_18000'),
(236, 'timezones_ARRAY_21600', 'arrays', 'timezones_ARRAY_21600'),
(237, 'timezones_ARRAY_25200', 'arrays', 'timezones_ARRAY_25200'),
(238, 'timezones_ARRAY_28800', 'arrays', 'timezones_ARRAY_28800'),
(239, 'timezones_ARRAY_32400', 'arrays', 'timezones_ARRAY_32400'),
(240, 'timezones_ARRAY_3600', 'arrays', 'timezones_ARRAY_3600'),
(241, 'timezones_ARRAY_36000', 'arrays', 'timezones_ARRAY_36000'),
(242, 'timezones_ARRAY_39600', 'arrays', 'timezones_ARRAY_39600'),
(243, 'timezones_ARRAY_43200', 'arrays', 'timezones_ARRAY_43200'),
(244, 'timezones_ARRAY_46800', 'arrays', 'timezones_ARRAY_46800'),
(245, 'timezones_ARRAY_7200', 'arrays', 'timezones_ARRAY_7200'),
(246, 'u_statarr_ARRAY_F', 'arrays', 'u_statarr_ARRAY_F'),
(247, 'u_statarr_ARRAY_T', 'arrays', 'u_statarr_ARRAY_T'),
(248, '_yesno_ARRAY_F', 'arrays', '_yesno_ARRAY_F'),
(249, '_yesno_ARRAY_T', 'arrays', '_yesno_ARRAY_T'),
(274, 'menuCalendar', 'backend', 'Menu / Calendar'),
(275, 'menuEvents', 'backend', 'Menu / Events'),
(276, 'menuCategories', 'backend', 'Menu / Categories'),
(277, 'lblAddCategory', 'backend', 'Add category'),
(278, 'lblCategory', 'backend', 'Label Category'),
(279, 'error_titles_ARRAY_AC01', 'arrays', 'error_titles_ARRAY_AC01'),
(280, 'error_titles_ARRAY_AC03', 'arrays', 'error_titles_ARRAY_AC03'),
(281, 'error_titles_ARRAY_AC04', 'arrays', 'error_titles_ARRAY_AC04'),
(282, 'error_titles_ARRAY_AC08', 'arrays', 'error_titles_ARRAY_AC08'),
(283, 'error_bodies_ARRAY_AC01', 'arrays', 'error_bodies_ARRAY_AC01'),
(284, 'error_bodies_ARRAY_AC03', 'arrays', 'error_bodies_ARRAY_AC03'),
(285, 'error_bodies_ARRAY_AC04', 'arrays', 'error_bodies_ARRAY_AC04'),
(286, 'error_bodies_ARRAY_AC08', 'arrays', 'error_bodies_ARRAY_AC08'),
(287, 'lblUpdateCategory', 'backend', 'Label Update category'),
(288, 'error_titles_ARRAY_AE01', 'arrays', 'error_titles_ARRAY_AE01'),
(289, 'error_titles_ARRAY_AE03', 'arrays', 'error_titles_ARRAY_AE03'),
(290, 'error_titles_ARRAY_AE04', 'arrays', 'error_titles_ARRAY_AE04'),
(291, 'error_titles_ARRAY_AE08', 'arrays', 'error_titles_ARRAY_AE08'),
(292, 'error_bodies_ARRAY_AE01', 'arrays', 'error_bodies_ARRAY_AE01'),
(293, 'error_bodies_ARRAY_AE03', 'arrays', 'error_bodies_ARRAY_AE03'),
(294, 'error_bodies_ARRAY_AE04', 'arrays', 'error_bodies_ARRAY_AE04'),
(295, 'error_bodies_ARRAY_AE08', 'arrays', 'error_bodies_ARRAY_AE08'),
(296, 'lblAddEvent', 'backend', 'Label Add event'),
(297, 'lblEventDate', 'backend', 'Label Event date'),
(298, 'lblEventTime', 'backend', 'Label Event time'),
(299, 'lblEventTitle', 'backend', 'Label Event title'),
(300, 'lblEndTime', 'backend', 'Label End time'),
(301, 'lblStartTime', 'backend', 'Label Start time'),
(326, 'opt_o_time_format', 'backend', 'Options / Time format'),
(327, 'opt_o_layout', 'backend', 'Options / Layout'),
(328, 'opt_o_enable_categories', 'backend', 'Options / Enable categories'),
(329, 'opt_o_enable_monthly_view', 'backend', 'Options / Enable monthly view'),
(330, 'opt_o_enable_list_view', 'backend', 'Options / Enable list view'),
(331, 'opt_o_default_view', 'backend', 'Options / Default view'),
(332, 'lblDescription', 'backend', 'Description'),
(333, 'lblRepeat', 'backend', 'Labe Repeat'),
(334, 'repeatarr_ARRAY_daily', 'arrays', 'repeatarr_ARRAY_daily'),
(335, 'repeatarr_ARRAY_weekly', 'arrays', 'repeatarr_ARRAY_weekly'),
(336, 'repeatarr_ARRAY_monthly', 'arrays', 'repeatarr_ARRAY_monthly'),
(337, 'repeatarr_ARRAY_quarterly', 'arrays', 'repeatarr_ARRAY_quarterly'),
(338, 'repeatarr_ARRAY_yearly', 'arrays', 'repeatarr_ARRAY_yearly'),
(339, 'repeatarr_ARRAY_custom', 'arrays', 'repeatarr_ARRAY_custom'),
(340, 'repeatarr_ARRAY_none', 'arrays', 'repeatarr_ARRAY_none'),
(341, 'lblEndRecurringOn', 'backend', 'Label End recurring on'),
(342, 'lblOrRepeat', 'backend', 'Label Or repeat'),
(343, 'lblTimes', 'backend', 'Label Times'),
(344, 'lblEach', 'backend', 'Label each'),
(346, 'lblRepeatEveryDay', 'backend', 'Label Repeat daily'),
(347, 'lblRepeatEveryWeek', 'backend', 'Label Repeat weekly'),
(348, 'lblRepeatEveryQuarter', 'backend', 'Label Repeat quarterly'),
(349, 'lblRepeatEveryYear', 'backend', 'Label Repeat yearly'),
(350, 'lblOn', 'backend', 'Label On'),
(351, 'lblOfTheMonth', 'backend', 'Label of the month'),
(352, 'lblOrEach', 'backend', 'Label Or each'),
(353, 'monthly_each_ARRAY_first', 'arrays', 'montly_each_ARRAY_first'),
(354, 'monthly_each_ARRAY_second', 'arrays', 'montly_each_ARRAY_second'),
(355, 'monthly_each_ARRAY_third', 'arrays', 'montly_each_ARRAY_third'),
(356, 'monthly_each_ARRAY_fourth', 'arrays', 'montly_each_ARRAY_fourth'),
(357, 'monthly_date_ARRAY_0', 'arrays', 'monthly_date_ARRAY_0'),
(358, 'monthly_date_ARRAY_1', 'arrays', 'monthly_date_ARRAY_1'),
(359, 'monthly_date_ARRAY_2', 'arrays', 'monthly_date_ARRAY_2'),
(360, 'monthly_date_ARRAY_3', 'arrays', 'monthly_date_ARRAY_3'),
(361, 'monthly_date_ARRAY_4', 'arrays', 'monthly_date_ARRAY_4'),
(362, 'monthly_date_ARRAY_5', 'arrays', 'monthly_date_ARRAY_5'),
(363, 'monthly_date_ARRAY_6', 'arrays', 'monthly_date_ARRAY_6'),
(364, 'monthly_date_ARRAY_8', 'arrays', 'monthly_date_ARRAY_8'),
(365, 'monthly_date_ARRAY_9', 'arrays', 'monthly_date_ARRAY_9'),
(366, 'monthly_date_ARRAY_10', 'arrays', 'monthly_date_ARRAY_10'),
(367, 'monthly_date_ARRAY_11', 'arrays', 'monthly_date_ARRAY_11'),
(368, 'monthly_date_ARRAY_12', 'arrays', 'monthly_date_ARRAY_12'),
(369, 'monthly_date_ARRAY_13', 'arrays', 'monthly_date_ARRAY_13'),
(370, 'monthly_date_ARRAY_14', 'arrays', 'monthly_date_ARRAY_14'),
(371, 'monthly_date_ARRAY_15', 'arrays', 'monthly_date_ARRAY_15'),
(372, 'monthly_date_ARRAY_16', 'arrays', 'monthly_date_ARRAY_16'),
(373, 'monthly_date_ARRAY_17', 'arrays', 'monthly_date_ARRAY_17'),
(374, 'monthly_date_ARRAY_18', 'arrays', 'monthly_date_ARRAY_18'),
(375, 'monthly_date_ARRAY_19', 'arrays', 'monthly_date_ARRAY_19'),
(376, 'monthly_date_ARRAY_20', 'arrays', 'monthly_date_ARRAY_20'),
(377, 'monthly_date_ARRAY_21', 'arrays', 'monthly_date_ARRAY_21'),
(378, 'monthly_date_ARRAY_22', 'arrays', 'monthly_date_ARRAY_22'),
(379, 'monthly_date_ARRAY_23', 'arrays', 'monthly_date_ARRAY_23'),
(380, 'monthly_date_ARRAY_24', 'arrays', 'monthly_date_ARRAY_24'),
(381, 'monthly_date_ARRAY_25', 'arrays', 'monthly_date_ARRAY_25'),
(382, 'monthly_date_ARRAY_26', 'arrays', 'monthly_date_ARRAY_26'),
(383, 'monthly_date_ARRAY_27', 'arrays', 'monthly_date_ARRAY_27'),
(384, 'monthly_date_ARRAY_28', 'arrays', 'monthly_date_ARRAY_28'),
(385, 'monthly_date_ARRAY_29', 'arrays', 'monthly_date_ARRAY_29'),
(386, 'monthly_date_ARRAY_30', 'arrays', 'monthly_date_ARRAY_30'),
(387, 'monthly_date_ARRAY_31', 'arrays', 'monthly_date_ARRAY_31'),
(388, 'lnkAddTime', 'backend', 'Link Add time'),
(389, 'lnkAddStartTime', 'backend', 'Link Add start time'),
(390, 'lnkAddEndTime', 'backend', 'Link Add end time'),
(391, 'lnkRemoveTime', 'backend', 'Link Remove time'),
(416, 'lblUpdateEvent', 'backend', 'Label Update event'),
(417, 'lblApplyRecurring', 'backend', 'Label Apply recurring'),
(418, 'front_label_choose', 'frontend', 'Front Label Choose'),
(419, 'menuInstall', 'backend', 'Menu / Install'),
(420, 'lblInstall', 'backend', 'Label Install'),
(421, 'lblInstallPhp1Title', 'backend', 'Label instruction title'),
(422, 'lblInstall_1', 'backend', 'Install step 1'),
(423, 'lblInstall_2', 'backend', 'Step 2'),
(424, 'opt_o_events_per_page', 'backend', 'Options / Events per page for list view'),
(425, 'opt_o_display_events', 'backend', 'Options / Display events for calendar view'),
(426, 'lblView', 'backend', 'Label / View'),
(427, 'lblHideSwitchIcons', 'backend', 'Label / Hide view switch icons'),
(428, 'lblHideCategories', 'backend', 'Label / Hide categories'),
(429, 'lblCSSFile', 'backend', 'Label / CSS file'),
(430, 'install_view_ARRAY_default', 'array', 'install_view_ARRAY_default'),
(431, 'install_view_ARRAY_list', 'array', 'install_view_ARRAY_list'),
(432, 'install_view_ARRAY_calendar', 'array', 'install_view_ARRAY_calendar'),
(433, 'install_view_ARRAY_monthly', 'array', 'install_view_ARRAY_monthly'),
(434, 'lblInstall_0', 'array', 'Install / Preparation step'),
(435, 'lblCalendarView', 'backend', 'Label Calendar view'),
(436, 'lblListView', 'backend', 'Label / List view'),
(437, 'lblMonthlyView', 'backend', 'Label / Monthly view'),
(438, 'lblInstallCSSExplanation', 'backend', 'Label / Install CSS explanation'),
(439, 'menuPreview', 'backend', 'Menu / Preview'),
(440, 'lblNoEventFound', 'backend', 'Label / No event found'),
(441, 'lblTime', 'backend', 'Label / Time'),
(442, 'lblDashLastLogin', 'backend', 'Label / Last login'),
(443, 'lblTodayEvents', 'backend', 'Label / Today events'),
(444, 'lblTotalEvents', 'backend', 'Label / Total events'),
(445, 'lblUpcomingEvents', 'backend', 'Label / Upcoming events'),
(446, 'lblUsers', 'backend', 'Label / Users'),
(447, 'layouts_ARRAY_layout_1', 'arrays', 'layouts_ARRAY_layout_1'),
(448, 'layouts_ARRAY_layout_2', 'arrays', 'layouts_ARRAY_layout_2'),
(449, 'layouts_ARRAY_layout_3', 'arrays', 'layouts_ARRAY_layout_3'),
(450, 'layouts_ARRAY_layout_4', 'arrays', 'layouts_ARRAY_layout_4'),
(451, 'layouts_ARRAY_layout_5', 'arrays', 'layouts_ARRAY_layout_5'),
(452, 'pec_delete_confirmation', 'backend', 'pec_delete_confirmation'),
(453, 'opt_o_enable_tooltip', 'backend', 'Options / Enable tooltip'),
(454, 'opt_o_event_title_position', 'backend', 'Options / Event title position'),
(455, 'monthly_date_ARRAY_7', 'array', 'monthly_date_ARRAY_7'),
(456, 'lblTimeError', 'backend', 'lblTimeError'),
(457, 'day_shortnames_ARRAY_0', 'arrays', 'day_shortnames_ARRAY_0'),
(458, 'day_shortnames_ARRAY_1', 'arrays', 'day_shortnames_ARRAY_1'),
(459, 'day_shortnames_ARRAY_2', 'arrays', 'day_shortnames_ARRAY_2'),
(460, 'day_shortnames_ARRAY_3', 'arrays', 'day_shortnames_ARRAY_3'),
(461, 'day_shortnames_ARRAY_4', 'arrays', 'day_shortnames_ARRAY_4'),
(462, 'day_shortnames_ARRAY_5', 'arrays', 'day_shortnames_ARRAY_5'),
(463, 'day_shortnames_ARRAY_6', 'arrays', 'day_shortnames_ARRAY_6'),
(464, 'lblSameCategory', 'backend', 'Label / Same category');

INSERT INTO `phpeventcalendar_multi_lang` (`id`, `foreign_id`, `model`, `locale`, `field`, `content`) VALUES
(NULL, 1, 'pjField', 1, 'title', 'Add language'),
(NULL, 1, 'pjField', 2, 'title', 'Add language'),
(NULL, 1, 'pjField', 3, 'title', 'Add language'),
(NULL, 2, 'pjField', 1, 'title', 'Password reminder'),
(NULL, 2, 'pjField', 2, 'title', 'Password reminder'),
(NULL, 2, 'pjField', 3, 'title', 'Password reminder'),
(NULL, 3, 'pjField', 1, 'title', 'Admin Login'),
(NULL, 3, 'pjField', 2, 'title', 'Admin Login'),
(NULL, 3, 'pjField', 3, 'title', 'Admin Login'),
(NULL, 4, 'pjField', 1, 'title', 'Back-end titles'),
(NULL, 4, 'pjField', 2, 'title', 'Back-end titles'),
(NULL, 4, 'pjField', 3, 'title', 'Back-end titles'),
(NULL, 5, 'pjField', 1, 'title', 'Add +'),
(NULL, 5, 'pjField', 2, 'title', 'Add +'),
(NULL, 5, 'pjField', 3, 'title', 'Add +'),
(NULL, 6, 'pjField', 1, 'title', '&laquo; Back'),
(NULL, 6, 'pjField', 2, 'title', 'Back'),
(NULL, 6, 'pjField', 3, 'title', 'Back'),
(NULL, 7, 'pjField', 1, 'title', 'Backup'),
(NULL, 7, 'pjField', 2, 'title', 'Backup'),
(NULL, 7, 'pjField', 3, 'title', 'Backup'),
(NULL, 8, 'pjField', 1, 'title', 'Cancel'),
(NULL, 8, 'pjField', 2, 'title', 'Cancel'),
(NULL, 8, 'pjField', 3, 'title', 'Cancel'),
(NULL, 9, 'pjField', 1, 'title', 'Continue'),
(NULL, 9, 'pjField', 2, 'title', 'Continue'),
(NULL, 9, 'pjField', 3, 'title', 'Continue'),
(NULL, 10, 'pjField', 1, 'title', 'Delete'),
(NULL, 10, 'pjField', 2, 'title', 'Delete'),
(NULL, 10, 'pjField', 3, 'title', 'Delete'),
(NULL, 11, 'pjField', 1, 'title', 'Login'),
(NULL, 11, 'pjField', 2, 'title', 'Login'),
(NULL, 11, 'pjField', 3, 'title', 'Login'),
(NULL, 12, 'pjField', 1, 'title', 'Reset'),
(NULL, 12, 'pjField', 2, 'title', 'Reset'),
(NULL, 12, 'pjField', 3, 'title', 'Reset'),
(NULL, 13, 'pjField', 1, 'title', 'Save'),
(NULL, 13, 'pjField', 2, 'title', 'Save'),
(NULL, 13, 'pjField', 3, 'title', 'Save'),
(NULL, 14, 'pjField', 1, 'title', 'Search'),
(NULL, 14, 'pjField', 2, 'title', 'Search'),
(NULL, 14, 'pjField', 3, 'title', 'Search'),
(NULL, 15, 'pjField', 1, 'title', 'Send'),
(NULL, 15, 'pjField', 2, 'title', 'Send'),
(NULL, 15, 'pjField', 3, 'title', 'Send'),
(NULL, 16, 'pjField', 1, 'title', 'Update'),
(NULL, 16, 'pjField', 2, 'title', 'Update'),
(NULL, 16, 'pjField', 3, 'title', 'Update'),
(NULL, 17, 'pjField', 1, 'title', 'DateTime'),
(NULL, 17, 'pjField', 2, 'title', 'DateTime'),
(NULL, 17, 'pjField', 3, 'title', 'DateTime'),
(NULL, 18, 'pjField', 1, 'title', 'Email'),
(NULL, 18, 'pjField', 2, 'title', 'Email'),
(NULL, 18, 'pjField', 3, 'title', 'Email'),
(NULL, 19, 'pjField', 1, 'title', 'Dear {Name},Your password: {Password}'),
(NULL, 19, 'pjField', 2, 'title', 'Dear {Name},Your password: {Password}'),
(NULL, 19, 'pjField', 3, 'title', 'Dear {Name},Your password: {Password}'),
(NULL, 20, 'pjField', 1, 'title', 'Password reminder'),
(NULL, 20, 'pjField', 2, 'title', 'Password reminder'),
(NULL, 20, 'pjField', 3, 'title', 'Password reminder'),
(NULL, 21, 'pjField', 1, 'title', 'Front-end titles'),
(NULL, 21, 'pjField', 2, 'title', 'Front-end titles'),
(NULL, 21, 'pjField', 3, 'title', 'Front-end titles'),
(NULL, 22, 'pjField', 1, 'title', 'Action confirmation'),
(NULL, 22, 'pjField', 2, 'title', 'Action confirmation'),
(NULL, 22, 'pjField', 3, 'title', 'Action confirmation'),
(NULL, 23, 'pjField', 1, 'title', 'Cancel'),
(NULL, 23, 'pjField', 2, 'title', 'Cancel'),
(NULL, 23, 'pjField', 3, 'title', 'Cancel'),
(NULL, 24, 'pjField', 1, 'title', 'Delete'),
(NULL, 24, 'pjField', 2, 'title', 'Delete'),
(NULL, 24, 'pjField', 3, 'title', 'Delete'),
(NULL, 25, 'pjField', 1, 'title', 'OK'),
(NULL, 25, 'pjField', 2, 'title', 'OK'),
(NULL, 25, 'pjField', 3, 'title', 'OK'),
(NULL, 26, 'pjField', 1, 'title', 'Choose Action'),
(NULL, 26, 'pjField', 2, 'title', 'Choose Action'),
(NULL, 26, 'pjField', 3, 'title', 'Choose Action'),
(NULL, 27, 'pjField', 1, 'title', 'Are you sure you want to delete selected record?'),
(NULL, 27, 'pjField', 2, 'title', 'Are you sure you want to delete selected record?'),
(NULL, 27, 'pjField', 3, 'title', 'Are you sure you want to delete selected record?'),
(NULL, 28, 'pjField', 1, 'title', 'Delete confirmation'),
(NULL, 28, 'pjField', 2, 'title', 'Delete confirmation'),
(NULL, 28, 'pjField', 3, 'title', 'Delete confirmation'),
(NULL, 29, 'pjField', 1, 'title', 'No records found'),
(NULL, 29, 'pjField', 2, 'title', 'No records found'),
(NULL, 29, 'pjField', 3, 'title', 'No records found'),
(NULL, 30, 'pjField', 1, 'title', 'Go to page:'),
(NULL, 30, 'pjField', 2, 'title', 'Go to page:'),
(NULL, 30, 'pjField', 3, 'title', 'Go to page:'),
(NULL, 31, 'pjField', 1, 'title', 'Items per page'),
(NULL, 31, 'pjField', 2, 'title', 'Items per page'),
(NULL, 31, 'pjField', 3, 'title', 'Items per page'),
(NULL, 32, 'pjField', 1, 'title', 'Next &raquo;'),
(NULL, 32, 'pjField', 2, 'title', 'Next &raquo;'),
(NULL, 32, 'pjField', 3, 'title', 'Next &raquo;'),
(NULL, 33, 'pjField', 1, 'title', 'Next page'),
(NULL, 33, 'pjField', 2, 'title', 'Next page'),
(NULL, 33, 'pjField', 3, 'title', 'Next page'),
(NULL, 34, 'pjField', 1, 'title', '&laquo; Prev'),
(NULL, 34, 'pjField', 2, 'title', '&laquo; Prev'),
(NULL, 34, 'pjField', 3, 'title', '&laquo; Prev'),
(NULL, 35, 'pjField', 1, 'title', 'Prev page'),
(NULL, 35, 'pjField', 2, 'title', 'Prev page'),
(NULL, 35, 'pjField', 3, 'title', 'Prev page'),
(NULL, 36, 'pjField', 1, 'title', 'Total items:'),
(NULL, 36, 'pjField', 2, 'title', 'Total items:'),
(NULL, 36, 'pjField', 3, 'title', 'Total items:'),
(NULL, 37, 'pjField', 1, 'title', 'Listing Address Body'),
(NULL, 37, 'pjField', 2, 'title', 'Listing Address Body'),
(NULL, 37, 'pjField', 3, 'title', 'Listing Address Body'),
(NULL, 38, 'pjField', 1, 'title', 'Listing Address Title'),
(NULL, 38, 'pjField', 2, 'title', 'Listing Address Title'),
(NULL, 38, 'pjField', 3, 'title', 'Listing Address Title'),
(NULL, 39, 'pjField', 1, 'title', 'Listing Bookings Body'),
(NULL, 39, 'pjField', 2, 'title', 'Listing Bookings Body'),
(NULL, 39, 'pjField', 3, 'title', 'Listing Bookings Body'),
(NULL, 40, 'pjField', 1, 'title', 'Listing Bookings Title'),
(NULL, 40, 'pjField', 2, 'title', 'Listing Bookings Title'),
(NULL, 40, 'pjField', 3, 'title', 'Listing Bookings Title'),
(NULL, 41, 'pjField', 1, 'title', 'Listing Contact Body'),
(NULL, 41, 'pjField', 2, 'title', 'Listing Contact Body'),
(NULL, 41, 'pjField', 3, 'title', 'Listing Contact Body'),
(NULL, 42, 'pjField', 1, 'title', 'Listing Contact Title'),
(NULL, 42, 'pjField', 2, 'title', 'Listing Contact Title'),
(NULL, 42, 'pjField', 3, 'title', 'Listing Contact Title'),
(NULL, 43, 'pjField', 1, 'title', 'Extend exp.date Body'),
(NULL, 43, 'pjField', 2, 'title', 'Extend exp.date Body'),
(NULL, 43, 'pjField', 3, 'title', 'Extend exp.date Body'),
(NULL, 44, 'pjField', 1, 'title', 'Extend exp.date Title'),
(NULL, 44, 'pjField', 2, 'title', 'Extend exp.date Title'),
(NULL, 44, 'pjField', 3, 'title', 'Extend exp.date Title'),
(NULL, 45, 'pjField', 1, 'title', 'Listing Prices Body'),
(NULL, 45, 'pjField', 2, 'title', 'Listing Prices Body'),
(NULL, 45, 'pjField', 3, 'title', 'Listing Prices Body'),
(NULL, 46, 'pjField', 1, 'title', 'Listing Prices Title'),
(NULL, 46, 'pjField', 2, 'title', 'Listing Prices Title'),
(NULL, 46, 'pjField', 3, 'title', 'Listing Prices Title'),
(NULL, 47, 'pjField', 1, 'title', 'Languages Array Body'),
(NULL, 47, 'pjField', 2, 'title', 'Languages Array Body'),
(NULL, 47, 'pjField', 3, 'title', 'Languages Array Body'),
(NULL, 48, 'pjField', 1, 'title', 'Languages Arrays Title'),
(NULL, 48, 'pjField', 2, 'title', 'Languages Arrays Title'),
(NULL, 48, 'pjField', 3, 'title', 'Languages Arrays Title'),
(NULL, 49, 'pjField', 1, 'title', 'Languages Backend Body'),
(NULL, 49, 'pjField', 2, 'title', 'Languages Backend Body'),
(NULL, 49, 'pjField', 3, 'title', 'Languages Backend Body'),
(NULL, 50, 'pjField', 1, 'title', 'Languages Backend Title'),
(NULL, 50, 'pjField', 2, 'title', 'Languages Backend Title'),
(NULL, 50, 'pjField', 3, 'title', 'Languages Backend Title'),
(NULL, 51, 'pjField', 1, 'title', 'Languages Body'),
(NULL, 51, 'pjField', 2, 'title', 'Languages Body'),
(NULL, 51, 'pjField', 3, 'title', 'Languages Body'),
(NULL, 52, 'pjField', 1, 'title', 'Languages Frontend Body'),
(NULL, 52, 'pjField', 2, 'title', 'Languages Frontend Body'),
(NULL, 52, 'pjField', 3, 'title', 'Languages Frontend Body'),
(NULL, 53, 'pjField', 1, 'title', 'Languages Frontend Title'),
(NULL, 53, 'pjField', 2, 'title', 'Languages Frontend Title'),
(NULL, 53, 'pjField', 3, 'title', 'Languages Frontend Title'),
(NULL, 54, 'pjField', 1, 'title', 'Languages Title'),
(NULL, 54, 'pjField', 2, 'title', 'Languages Title'),
(NULL, 54, 'pjField', 3, 'title', 'Languages Title'),
(NULL, 55, 'pjField', 1, 'title', 'Add user'),
(NULL, 55, 'pjField', 2, 'title', 'Add user'),
(NULL, 55, 'pjField', 3, 'title', 'Add user'),
(NULL, 56, 'pjField', 1, 'title', 'Backup database'),
(NULL, 56, 'pjField', 2, 'title', 'Backup database'),
(NULL, 56, 'pjField', 3, 'title', 'Backup database'),
(NULL, 57, 'pjField', 1, 'title', 'Backup files'),
(NULL, 57, 'pjField', 2, 'title', 'Backup files'),
(NULL, 57, 'pjField', 3, 'title', 'Backup files'),
(NULL, 58, 'pjField', 1, 'title', 'Choose'),
(NULL, 58, 'pjField', 2, 'title', 'Choose'),
(NULL, 58, 'pjField', 3, 'title', 'Choose'),
(NULL, 59, 'pjField', 1, 'title', 'days'),
(NULL, 59, 'pjField', 2, 'title', 'days'),
(NULL, 59, 'pjField', 3, 'title', 'days'),
(NULL, 60, 'pjField', 1, 'title', 'Delete'),
(NULL, 60, 'pjField', 2, 'title', 'Delete'),
(NULL, 60, 'pjField', 3, 'title', 'Delete'),
(NULL, 61, 'pjField', 1, 'title', 'Error'),
(NULL, 61, 'pjField', 2, 'title', 'Error'),
(NULL, 61, 'pjField', 3, 'title', 'Error'),
(NULL, 62, 'pjField', 1, 'title', 'Export'),
(NULL, 62, 'pjField', 2, 'title', 'Export'),
(NULL, 62, 'pjField', 3, 'title', 'Export'),
(NULL, 63, 'pjField', 1, 'title', 'Forgot password'),
(NULL, 63, 'pjField', 2, 'title', 'Forgot password'),
(NULL, 63, 'pjField', 3, 'title', 'Forgot password'),
(NULL, 64, 'pjField', 1, 'title', 'IP address'),
(NULL, 64, 'pjField', 2, 'title', 'IP address'),
(NULL, 64, 'pjField', 3, 'title', 'IP address'),
(NULL, 65, 'pjField', 1, 'title', 'Is confirmed'),
(NULL, 65, 'pjField', 2, 'title', 'Is Active'),
(NULL, 65, 'pjField', 3, 'title', 'Is Active'),
(NULL, 66, 'pjField', 1, 'title', 'Name'),
(NULL, 66, 'pjField', 2, 'title', 'Name'),
(NULL, 66, 'pjField', 3, 'title', 'Name'),
(NULL, 67, 'pjField', 1, 'title', 'No'),
(NULL, 67, 'pjField', 2, 'title', 'No'),
(NULL, 67, 'pjField', 3, 'title', 'No'),
(NULL, 68, 'pjField', 1, 'title', 'Option'),
(NULL, 68, 'pjField', 2, 'title', 'Option'),
(NULL, 68, 'pjField', 3, 'title', 'Option'),
(NULL, 69, 'pjField', 1, 'title', 'Option list'),
(NULL, 69, 'pjField', 2, 'title', 'Option list'),
(NULL, 69, 'pjField', 3, 'title', 'Option list'),
(NULL, 70, 'pjField', 1, 'title', 'Role'),
(NULL, 70, 'pjField', 2, 'title', 'Role'),
(NULL, 70, 'pjField', 3, 'title', 'Role'),
(NULL, 71, 'pjField', 1, 'title', 'Status'),
(NULL, 71, 'pjField', 2, 'title', 'Status'),
(NULL, 71, 'pjField', 3, 'title', 'Status'),
(NULL, 72, 'pjField', 1, 'title', 'Type'),
(NULL, 72, 'pjField', 2, 'title', 'Type'),
(NULL, 72, 'pjField', 3, 'title', 'Type'),
(NULL, 73, 'pjField', 1, 'title', 'Update user'),
(NULL, 73, 'pjField', 2, 'title', 'Update user'),
(NULL, 73, 'pjField', 3, 'title', 'Update user'),
(NULL, 74, 'pjField', 1, 'title', 'Registration date/time'),
(NULL, 74, 'pjField', 2, 'title', 'Registration date/time'),
(NULL, 74, 'pjField', 3, 'title', 'Registration date/time'),
(NULL, 75, 'pjField', 1, 'title', 'Value'),
(NULL, 75, 'pjField', 2, 'title', 'Value'),
(NULL, 75, 'pjField', 3, 'title', 'Value'),
(NULL, 76, 'pjField', 1, 'title', 'Yes'),
(NULL, 76, 'pjField', 2, 'title', 'Yes'),
(NULL, 76, 'pjField', 3, 'title', 'Yes'),
(NULL, 77, 'pjField', 1, 'title', 'Back'),
(NULL, 77, 'pjField', 2, 'title', 'Back'),
(NULL, 77, 'pjField', 3, 'title', 'Back'),
(NULL, 78, 'pjField', 1, 'title', 'Arrays titles'),
(NULL, 78, 'pjField', 2, 'title', 'Arrays titles'),
(NULL, 78, 'pjField', 3, 'title', 'Arrays titles'),
(NULL, 79, 'pjField', 1, 'title', 'Languages'),
(NULL, 79, 'pjField', 2, 'title', 'Languages'),
(NULL, 79, 'pjField', 3, 'title', 'Languages'),
(NULL, 80, 'pjField', 1, 'title', 'Flag'),
(NULL, 80, 'pjField', 2, 'title', 'Flag'),
(NULL, 80, 'pjField', 3, 'title', 'Flag'),
(NULL, 81, 'pjField', 1, 'title', 'Is default'),
(NULL, 81, 'pjField', 2, 'title', 'Is default'),
(NULL, 81, 'pjField', 3, 'title', 'Is default'),
(NULL, 82, 'pjField', 1, 'title', 'Order'),
(NULL, 82, 'pjField', 2, 'title', 'Order'),
(NULL, 82, 'pjField', 3, 'title', 'Order'),
(NULL, 83, 'pjField', 1, 'title', 'Title'),
(NULL, 83, 'pjField', 2, 'title', 'Title'),
(NULL, 83, 'pjField', 3, 'title', 'Title'),
(NULL, 84, 'pjField', 1, 'title', 'Backup'),
(NULL, 84, 'pjField', 2, 'title', 'Backup'),
(NULL, 84, 'pjField', 3, 'title', 'Backup'),
(NULL, 85, 'pjField', 1, 'title', 'Dashboard'),
(NULL, 85, 'pjField', 2, 'title', 'Dashboard'),
(NULL, 85, 'pjField', 3, 'title', 'Dashboard'),
(NULL, 86, 'pjField', 1, 'title', 'Multi Lang'),
(NULL, 86, 'pjField', 2, 'title', 'Multi Lang'),
(NULL, 86, 'pjField', 3, 'title', 'Multi Lang'),
(NULL, 87, 'pjField', 1, 'title', 'Languages'),
(NULL, 87, 'pjField', 2, 'title', 'Languages'),
(NULL, 88, 'pjField', 1, 'title', 'Logout'),
(NULL, 88, 'pjField', 2, 'title', 'Logout'),
(NULL, 88, 'pjField', 3, 'title', 'Logout'),
(NULL, 89, 'pjField', 1, 'title', 'Options'),
(NULL, 89, 'pjField', 2, 'title', 'Options'),
(NULL, 89, 'pjField', 3, 'title', 'Options'),
(NULL, 90, 'pjField', 1, 'title', 'Plugins'),
(NULL, 90, 'pjField', 2, 'title', 'Plugins'),
(NULL, 90, 'pjField', 3, 'title', 'Plugins'),
(NULL, 91, 'pjField', 1, 'title', 'Profile'),
(NULL, 91, 'pjField', 2, 'title', 'Profile'),
(NULL, 91, 'pjField', 3, 'title', 'Profile'),
(NULL, 92, 'pjField', 1, 'title', 'Users'),
(NULL, 92, 'pjField', 2, 'title', 'Users'),
(NULL, 92, 'pjField', 3, 'title', 'Users'),
(NULL, 93, 'pjField', 1, 'title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'),
(NULL, 93, 'pjField', 2, 'title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'),
(NULL, 93, 'pjField', 3, 'title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'),
(NULL, 94, 'pjField', 1, 'title', 'Currency'),
(NULL, 94, 'pjField', 2, 'title', 'Currency'),
(NULL, 94, 'pjField', 3, 'title', 'Currency'),
(NULL, 95, 'pjField', 1, 'title', 'Date format'),
(NULL, 95, 'pjField', 2, 'title', 'Date format'),
(NULL, 95, 'pjField', 3, 'title', 'Date format'),
(NULL, 96, 'pjField', 1, 'title', 'Timezone'),
(NULL, 96, 'pjField', 2, 'title', 'Timezone'),
(NULL, 96, 'pjField', 3, 'title', 'Timezone'),
(NULL, 97, 'pjField', 1, 'title', 'First day of the week'),
(NULL, 97, 'pjField', 2, 'title', 'First day of the week'),
(NULL, 97, 'pjField', 3, 'title', 'First day of the week'),
(NULL, 98, 'pjField', 1, 'title', 'Password'),
(NULL, 98, 'pjField', 2, 'title', 'Password'),
(NULL, 98, 'pjField', 3, 'title', 'Password'),
(NULL, 99, 'pjField', 1, 'title', 'Active'),
(NULL, 99, 'pjField', 2, 'title', 'Active'),
(NULL, 99, 'pjField', 3, 'title', 'Active'),
(NULL, 100, 'pjField', 1, 'title', 'Delete selected'),
(NULL, 100, 'pjField', 2, 'title', 'Delete selected'),
(NULL, 100, 'pjField', 3, 'title', 'Delete selected'),
(NULL, 101, 'pjField', 1, 'title', 'Email address is already in use'),
(NULL, 101, 'pjField', 2, 'title', 'Email address is already in use'),
(NULL, 102, 'pjField', 1, 'title', 'Inactive'),
(NULL, 102, 'pjField', 2, 'title', 'Inactive'),
(NULL, 102, 'pjField', 3, 'title', 'Inactive'),
(NULL, 103, 'pjField', 1, 'title', 'Add Language'),
(NULL, 103, 'pjField', 2, 'title', 'Add Language'),
(NULL, 103, 'pjField', 3, 'title', 'Add Language'),
(NULL, 104, 'pjField', 1, 'title', 'Add as many languages as you need to your script. For each of the languages added you need to translate all the text titles.'),
(NULL, 104, 'pjField', 2, 'title', 'Add as many languages as you need to your script. For each of the languages added you need to translate all the text titles.'),
(NULL, 104, 'pjField', 3, 'title', 'Add as many languages as you need to your script. For each of the languages added you need to translate all the text titles.'),
(NULL, 105, 'pjField', 1, 'title', 'Languages'),
(NULL, 105, 'pjField', 2, 'title', 'Languages'),
(NULL, 105, 'pjField', 3, 'title', 'Languages'),
(NULL, 106, 'pjField', 1, 'title', 'Languages'),
(NULL, 106, 'pjField', 2, 'title', 'Languages'),
(NULL, 106, 'pjField', 3, 'title', 'Languages'),
(NULL, 107, 'pjField', 1, 'title', 'Field'),
(NULL, 107, 'pjField', 2, 'title', 'Field'),
(NULL, 107, 'pjField', 3, 'title', 'Field'),
(NULL, 108, 'pjField', 1, 'title', 'Flag'),
(NULL, 108, 'pjField', 2, 'title', 'Flag'),
(NULL, 108, 'pjField', 3, 'title', 'Flag'),
(NULL, 109, 'pjField', 1, 'title', 'Is default'),
(NULL, 109, 'pjField', 2, 'title', 'Is default'),
(NULL, 109, 'pjField', 3, 'title', 'Is default'),
(NULL, 110, 'pjField', 1, 'title', 'Order'),
(NULL, 110, 'pjField', 2, 'title', 'Order'),
(NULL, 110, 'pjField', 3, 'title', 'Order'),
(NULL, 111, 'pjField', 1, 'title', 'Title'),
(NULL, 111, 'pjField', 2, 'title', 'Title'),
(NULL, 111, 'pjField', 3, 'title', 'Title'),
(NULL, 112, 'pjField', 1, 'title', 'Type'),
(NULL, 112, 'pjField', 2, 'title', 'Type'),
(NULL, 112, 'pjField', 3, 'title', 'Type'),
(NULL, 113, 'pjField', 1, 'title', 'Value'),
(NULL, 113, 'pjField', 2, 'title', 'Value'),
(NULL, 113, 'pjField', 3, 'title', 'Value'),
(NULL, 114, 'pjField', 1, 'title', 'Titles'),
(NULL, 114, 'pjField', 2, 'title', 'Titles'),
(NULL, 114, 'pjField', 3, 'title', 'Titles'),
(NULL, 115, 'pjField', 1, 'title', 'Edit all page titles. Use the search box to quickly locate a title.'),
(NULL, 115, 'pjField', 2, 'title', 'Edit all page titles. Use the search box to quickly locate a title.'),
(NULL, 115, 'pjField', 3, 'title', 'Edit all page titles. Use the search box to quickly locate a title.'),
(NULL, 116, 'pjField', 1, 'title', 'Titles'),
(NULL, 116, 'pjField', 2, 'title', 'Titles'),
(NULL, 116, 'pjField', 3, 'title', 'Titles'),
(NULL, 117, 'pjField', 1, 'title', 'Special title'),
(NULL, 117, 'pjField', 2, 'title', 'Special title'),
(NULL, 117, 'pjField', 3, 'title', 'Special title'),
(NULL, 118, 'pjField', 1, 'title', 'Back-end title'),
(NULL, 118, 'pjField', 2, 'title', 'Back-end title'),
(NULL, 118, 'pjField', 3, 'title', 'Back-end title'),
(NULL, 119, 'pjField', 1, 'title', 'Front-end title'),
(NULL, 119, 'pjField', 2, 'title', 'Front-end title'),
(NULL, 119, 'pjField', 3, 'title', 'Front-end title'),
(NULL, 120, 'pjField', 1, 'title', 'Empty log'),
(NULL, 120, 'pjField', 2, 'title', 'Empty log'),
(NULL, 120, 'pjField', 3, 'title', 'Empty log'),
(NULL, 121, 'pjField', 1, 'title', 'Config log'),
(NULL, 121, 'pjField', 2, 'title', 'Config log'),
(NULL, 121, 'pjField', 3, 'title', 'Config log'),
(NULL, 122, 'pjField', 1, 'title', 'Log'),
(NULL, 122, 'pjField', 2, 'title', 'Log'),
(NULL, 122, 'pjField', 3, 'title', 'Log'),
(NULL, 123, 'pjField', 1, 'title', 'Revert status'),
(NULL, 123, 'pjField', 2, 'title', 'Revert status'),
(NULL, 123, 'pjField', 3, 'title', 'Revert status'),
(NULL, 124, 'pjField', 1, 'title', 'URL'),
(NULL, 124, 'pjField', 2, 'title', 'URL'),
(NULL, 124, 'pjField', 3, 'title', 'URL'),
(NULL, 125, 'pjField', 1, 'title', 'Username'),
(NULL, 125, 'pjField', 2, 'title', 'Username'),
(NULL, 125, 'pjField', 3, 'title', 'Username'),
(NULL, 126, 'pjField', 1, 'title', 'Sunday'),
(NULL, 126, 'pjField', 2, 'title', 'Sunday'),
(NULL, 126, 'pjField', 3, 'title', 'Sunday'),
(NULL, 127, 'pjField', 1, 'title', 'Monday'),
(NULL, 127, 'pjField', 2, 'title', 'Monday'),
(NULL, 127, 'pjField', 3, 'title', 'Monday'),
(NULL, 128, 'pjField', 1, 'title', 'Tuesday'),
(NULL, 128, 'pjField', 2, 'title', 'Tuesday'),
(NULL, 128, 'pjField', 3, 'title', 'Tuesday'),
(NULL, 129, 'pjField', 1, 'title', 'Wednesday'),
(NULL, 129, 'pjField', 2, 'title', 'Wednesday'),
(NULL, 129, 'pjField', 3, 'title', 'Wednesday'),
(NULL, 130, 'pjField', 1, 'title', 'Thursday'),
(NULL, 130, 'pjField', 2, 'title', 'Thursday'),
(NULL, 130, 'pjField', 3, 'title', 'Thursday'),
(NULL, 131, 'pjField', 1, 'title', 'Friday'),
(NULL, 131, 'pjField', 2, 'title', 'Friday'),
(NULL, 131, 'pjField', 3, 'title', 'Friday'),
(NULL, 132, 'pjField', 1, 'title', 'Saturday'),
(NULL, 132, 'pjField', 2, 'title', 'Saturday'),
(NULL, 132, 'pjField', 3, 'title', 'Saturday'),
(NULL, 133, 'pjField', 1, 'title', 'S'),
(NULL, 133, 'pjField', 2, 'title', 'S'),
(NULL, 133, 'pjField', 3, 'title', 'S'),
(NULL, 134, 'pjField', 1, 'title', 'M'),
(NULL, 134, 'pjField', 2, 'title', 'M'),
(NULL, 134, 'pjField', 3, 'title', 'M'),
(NULL, 135, 'pjField', 1, 'title', 'T'),
(NULL, 135, 'pjField', 2, 'title', 'T'),
(NULL, 135, 'pjField', 3, 'title', 'T'),
(NULL, 136, 'pjField', 1, 'title', 'W'),
(NULL, 136, 'pjField', 2, 'title', 'W'),
(NULL, 136, 'pjField', 3, 'title', 'W'),
(NULL, 137, 'pjField', 1, 'title', 'T'),
(NULL, 137, 'pjField', 2, 'title', 'T'),
(NULL, 137, 'pjField', 3, 'title', 'T'),
(NULL, 138, 'pjField', 1, 'title', 'F'),
(NULL, 138, 'pjField', 2, 'title', 'F'),
(NULL, 138, 'pjField', 3, 'title', 'F'),
(NULL, 139, 'pjField', 1, 'title', 'S'),
(NULL, 139, 'pjField', 2, 'title', 'S'),
(NULL, 139, 'pjField', 3, 'title', 'S'),
(NULL, 140, 'pjField', 1, 'title', 'Given email address is not associated with any account.'),
(NULL, 140, 'pjField', 2, 'title', 'Given email address is not associated with any account.'),
(NULL, 140, 'pjField', 3, 'title', 'Given email address is not associated with any account.'),
(NULL, 141, 'pjField', 1, 'title', 'For further instructions please check your mailbox.'),
(NULL, 141, 'pjField', 2, 'title', 'For further instructions please check your mailbox.'),
(NULL, 141, 'pjField', 3, 'title', 'For further instructions please check your mailbox.'),
(NULL, 142, 'pjField', 1, 'title', 'We''re sorry, please try again later.'),
(NULL, 142, 'pjField', 2, 'title', 'We''re sorry, please try again later.'),
(NULL, 142, 'pjField', 3, 'title', 'We''re sorry, please try again later.'),
(NULL, 143, 'pjField', 1, 'title', 'All the changes made to your profile have been saved.'),
(NULL, 143, 'pjField', 2, 'title', 'All the changes made to your profile have been saved.'),
(NULL, 143, 'pjField', 3, 'title', 'All the changes made to your profile have been saved.'),
(NULL, 144, 'pjField', 1, 'title', 'We recommend you to regularly back up your database and files to prevent any loss of information.'),
(NULL, 144, 'pjField', 2, 'title', 'We recommend you to regularly back up your database and files to prevent any loss of information.'),
(NULL, 144, 'pjField', 3, 'title', 'We recommend you to regularly back up your database and files to prevent any loss of information.'),
(NULL, 145, 'pjField', 1, 'title', 'All backup files have been saved.'),
(NULL, 145, 'pjField', 2, 'title', 'All backup files have been saved.'),
(NULL, 145, 'pjField', 3, 'title', 'All backup files have been saved.'),
(NULL, 146, 'pjField', 1, 'title', 'No option was selected.'),
(NULL, 146, 'pjField', 2, 'title', 'No option was selected.'),
(NULL, 146, 'pjField', 3, 'title', 'No option was selected.'),
(NULL, 147, 'pjField', 1, 'title', 'Backup not performed.'),
(NULL, 147, 'pjField', 2, 'title', 'Backup not performed.'),
(NULL, 147, 'pjField', 3, 'title', 'Backup not performed.'),
(NULL, 148, 'pjField', 1, 'title', 'All the changes made to titles have been saved.'),
(NULL, 148, 'pjField', 2, 'title', 'All the changes made to titles have been saved.'),
(NULL, 148, 'pjField', 3, 'title', 'All the changes made to titles have been saved.'),
(NULL, 149, 'pjField', 1, 'title', 'All the changes made to options have been saved.'),
(NULL, 149, 'pjField', 2, 'title', 'All the changes made to options have been saved.'),
(NULL, 149, 'pjField', 3, 'title', 'All the changes made to options have been saved.'),
(NULL, 150, 'pjField', 1, 'title', 'All the changes made to this user have been saved.'),
(NULL, 150, 'pjField', 2, 'title', 'All the changes made to this user have been saved.'),
(NULL, 150, 'pjField', 3, 'title', 'All the changes made to this user have been saved.'),
(NULL, 151, 'pjField', 1, 'title', 'All the changes made to this user have been saved.'),
(NULL, 151, 'pjField', 2, 'title', 'All the changes made to this user have been saved.'),
(NULL, 151, 'pjField', 3, 'title', 'All the changes made to this user have been saved.'),
(NULL, 152, 'pjField', 1, 'title', 'We are sorry, but the user has not been added.'),
(NULL, 152, 'pjField', 2, 'title', 'We are sorry, but the user has not been added.'),
(NULL, 152, 'pjField', 3, 'title', 'We are sorry, but the user has not been added.'),
(NULL, 153, 'pjField', 1, 'title', 'User your looking for is missing.'),
(NULL, 153, 'pjField', 2, 'title', 'User your looking for is missing.'),
(NULL, 153, 'pjField', 3, 'title', 'User your looking for is missing.'),
(NULL, 154, 'pjField', 1, 'title', 'All the changes made to titles have been saved.'),
(NULL, 154, 'pjField', 2, 'title', 'All the changes made to titles have been saved.'),
(NULL, 154, 'pjField', 3, 'title', 'All the changes made to titles have been saved.'),
(NULL, 155, 'pjField', 1, 'title', 'The config log have been updated.'),
(NULL, 155, 'pjField', 2, 'title', 'The config log have been updated.'),
(NULL, 155, 'pjField', 3, 'title', 'The config log have been updated.'),
(NULL, 156, 'pjField', 1, 'title', 'Account not found!'),
(NULL, 156, 'pjField', 2, 'title', 'Account not found!'),
(NULL, 156, 'pjField', 3, 'title', 'Account not found!'),
(NULL, 157, 'pjField', 1, 'title', 'Password send!'),
(NULL, 157, 'pjField', 2, 'title', 'Password send!'),
(NULL, 157, 'pjField', 3, 'title', 'Password send!'),
(NULL, 158, 'pjField', 1, 'title', 'Password not send!'),
(NULL, 158, 'pjField', 2, 'title', 'Password not send!'),
(NULL, 158, 'pjField', 3, 'title', 'Password not send!'),
(NULL, 159, 'pjField', 1, 'title', 'Profile updated!'),
(NULL, 159, 'pjField', 2, 'title', 'Profile updated!'),
(NULL, 159, 'pjField', 3, 'title', 'Profile updated!'),
(NULL, 160, 'pjField', 1, 'title', 'Backup'),
(NULL, 160, 'pjField', 2, 'title', 'Backup'),
(NULL, 160, 'pjField', 3, 'title', 'Backup'),
(NULL, 161, 'pjField', 1, 'title', 'Backup complete!'),
(NULL, 161, 'pjField', 2, 'title', 'Backup complete!'),
(NULL, 161, 'pjField', 3, 'title', 'Backup complete!'),
(NULL, 162, 'pjField', 1, 'title', 'Backup failed!'),
(NULL, 162, 'pjField', 2, 'title', 'Backup failed!'),
(NULL, 162, 'pjField', 3, 'title', 'Backup failed!'),
(NULL, 163, 'pjField', 1, 'title', 'Backup failed!'),
(NULL, 163, 'pjField', 2, 'title', 'Backup failed!'),
(NULL, 163, 'pjField', 3, 'title', 'Backup failed!'),
(NULL, 164, 'pjField', 1, 'title', 'Options updated!'),
(NULL, 164, 'pjField', 2, 'title', 'Options updated!'),
(NULL, 164, 'pjField', 3, 'title', 'Options updated!'),
(NULL, 165, 'pjField', 1, 'title', 'User updated!'),
(NULL, 165, 'pjField', 2, 'title', 'User updated!'),
(NULL, 165, 'pjField', 3, 'title', 'User updated!'),
(NULL, 166, 'pjField', 1, 'title', 'User added!'),
(NULL, 166, 'pjField', 2, 'title', 'User added!'),
(NULL, 166, 'pjField', 3, 'title', 'User added!'),
(NULL, 167, 'pjField', 1, 'title', 'User failed to add.'),
(NULL, 167, 'pjField', 2, 'title', 'User failed to add.'),
(NULL, 167, 'pjField', 3, 'title', 'User failed to add.'),
(NULL, 168, 'pjField', 1, 'title', 'User not found.'),
(NULL, 168, 'pjField', 2, 'title', 'User not found.'),
(NULL, 168, 'pjField', 3, 'title', 'User not found.'),
(NULL, 169, 'pjField', 1, 'title', 'Titles Updated'),
(NULL, 169, 'pjField', 2, 'title', 'Titles Updated'),
(NULL, 169, 'pjField', 3, 'title', 'Titles Updated'),
(NULL, 170, 'pjField', 1, 'title', 'Config log updated.'),
(NULL, 170, 'pjField', 2, 'title', 'Config log updated.'),
(NULL, 170, 'pjField', 3, 'title', 'Config log updated.'),
(NULL, 171, 'pjField', 1, 'title', 'Active'),
(NULL, 171, 'pjField', 2, 'title', 'Active'),
(NULL, 171, 'pjField', 3, 'title', 'Active'),
(NULL, 172, 'pjField', 1, 'title', 'Inactive'),
(NULL, 172, 'pjField', 2, 'title', 'Inactive'),
(NULL, 172, 'pjField', 3, 'title', 'Inactive'),
(NULL, 173, 'pjField', 1, 'title', 'Wrong username or password'),
(NULL, 173, 'pjField', 2, 'title', 'Wrong username or password'),
(NULL, 173, 'pjField', 3, 'title', 'Wrong username or password'),
(NULL, 174, 'pjField', 1, 'title', 'Access denied'),
(NULL, 174, 'pjField', 2, 'title', 'Access denied'),
(NULL, 174, 'pjField', 3, 'title', 'Access denied'),
(NULL, 175, 'pjField', 1, 'title', 'Account is disabled'),
(NULL, 175, 'pjField', 2, 'title', 'Account is disabled'),
(NULL, 175, 'pjField', 3, 'title', 'Account is disabled'),
(NULL, 176, 'pjField', 1, 'title', 'January'),
(NULL, 176, 'pjField', 2, 'title', 'January'),
(NULL, 176, 'pjField', 3, 'title', 'January'),
(NULL, 177, 'pjField', 1, 'title', 'October'),
(NULL, 177, 'pjField', 2, 'title', 'October'),
(NULL, 177, 'pjField', 3, 'title', 'October'),
(NULL, 178, 'pjField', 1, 'title', 'November'),
(NULL, 178, 'pjField', 2, 'title', 'November'),
(NULL, 178, 'pjField', 3, 'title', 'November'),
(NULL, 179, 'pjField', 1, 'title', 'December'),
(NULL, 179, 'pjField', 2, 'title', 'December'),
(NULL, 179, 'pjField', 3, 'title', 'December'),
(NULL, 180, 'pjField', 1, 'title', 'February'),
(NULL, 180, 'pjField', 2, 'title', 'February'),
(NULL, 180, 'pjField', 3, 'title', 'February'),
(NULL, 181, 'pjField', 1, 'title', 'March'),
(NULL, 181, 'pjField', 2, 'title', 'March'),
(NULL, 181, 'pjField', 3, 'title', 'March'),
(NULL, 182, 'pjField', 1, 'title', 'April'),
(NULL, 182, 'pjField', 2, 'title', 'April'),
(NULL, 182, 'pjField', 3, 'title', 'April'),
(NULL, 183, 'pjField', 1, 'title', 'May'),
(NULL, 183, 'pjField', 2, 'title', 'May'),
(NULL, 183, 'pjField', 3, 'title', 'May'),
(NULL, 184, 'pjField', 1, 'title', 'June'),
(NULL, 184, 'pjField', 2, 'title', 'June'),
(NULL, 184, 'pjField', 3, 'title', 'June'),
(NULL, 185, 'pjField', 1, 'title', 'July'),
(NULL, 185, 'pjField', 2, 'title', 'July'),
(NULL, 185, 'pjField', 3, 'title', 'July'),
(NULL, 186, 'pjField', 1, 'title', 'August'),
(NULL, 186, 'pjField', 2, 'title', 'August'),
(NULL, 186, 'pjField', 3, 'title', 'August'),
(NULL, 187, 'pjField', 1, 'title', 'September'),
(NULL, 187, 'pjField', 2, 'title', 'September'),
(NULL, 187, 'pjField', 3, 'title', 'September'),
(NULL, 188, 'pjField', 1, 'title', 'Dr.'),
(NULL, 188, 'pjField', 2, 'title', 'Dr.'),
(NULL, 188, 'pjField', 3, 'title', 'Dr.'),
(NULL, 189, 'pjField', 1, 'title', 'Miss'),
(NULL, 189, 'pjField', 2, 'title', 'Miss'),
(NULL, 189, 'pjField', 3, 'title', 'Miss'),
(NULL, 190, 'pjField', 1, 'title', 'Mr.'),
(NULL, 190, 'pjField', 2, 'title', 'Mr.'),
(NULL, 190, 'pjField', 3, 'title', 'Mr.'),
(NULL, 191, 'pjField', 1, 'title', 'Mrs.'),
(NULL, 191, 'pjField', 2, 'title', 'Mrs.'),
(NULL, 191, 'pjField', 3, 'title', 'Mrs.'),
(NULL, 192, 'pjField', 1, 'title', 'Ms.'),
(NULL, 192, 'pjField', 2, 'title', 'Ms.'),
(NULL, 192, 'pjField', 3, 'title', 'Ms.'),
(NULL, 193, 'pjField', 1, 'title', 'Other'),
(NULL, 193, 'pjField', 2, 'title', 'Other'),
(NULL, 193, 'pjField', 3, 'title', 'Other'),
(NULL, 194, 'pjField', 1, 'title', 'Prof.'),
(NULL, 194, 'pjField', 2, 'title', 'Prof.'),
(NULL, 194, 'pjField', 3, 'title', 'Prof.'),
(NULL, 195, 'pjField', 1, 'title', 'Rev.'),
(NULL, 195, 'pjField', 2, 'title', 'Rev.'),
(NULL, 195, 'pjField', 3, 'title', 'Rev.'),
(NULL, 196, 'pjField', 1, 'title', 'Jan'),
(NULL, 196, 'pjField', 2, 'title', 'Jan'),
(NULL, 196, 'pjField', 3, 'title', 'Jan'),
(NULL, 197, 'pjField', 1, 'title', 'Oct'),
(NULL, 197, 'pjField', 2, 'title', 'Oct'),
(NULL, 197, 'pjField', 3, 'title', 'Oct'),
(NULL, 198, 'pjField', 1, 'title', 'Nov'),
(NULL, 198, 'pjField', 2, 'title', 'Nov'),
(NULL, 198, 'pjField', 3, 'title', 'Nov'),
(NULL, 199, 'pjField', 1, 'title', 'Dec'),
(NULL, 199, 'pjField', 2, 'title', 'Dec'),
(NULL, 199, 'pjField', 3, 'title', 'Dec'),
(NULL, 200, 'pjField', 1, 'title', 'Feb'),
(NULL, 200, 'pjField', 2, 'title', 'Feb'),
(NULL, 200, 'pjField', 3, 'title', 'Feb'),
(NULL, 201, 'pjField', 1, 'title', 'Mar'),
(NULL, 201, 'pjField', 2, 'title', 'Mar'),
(NULL, 201, 'pjField', 3, 'title', 'Mar'),
(NULL, 202, 'pjField', 1, 'title', 'Apr'),
(NULL, 202, 'pjField', 2, 'title', 'Apr'),
(NULL, 202, 'pjField', 3, 'title', 'Apr'),
(NULL, 203, 'pjField', 1, 'title', 'May'),
(NULL, 203, 'pjField', 2, 'title', 'May'),
(NULL, 203, 'pjField', 3, 'title', 'May'),
(NULL, 204, 'pjField', 1, 'title', 'Jun'),
(NULL, 204, 'pjField', 2, 'title', 'Jun'),
(NULL, 204, 'pjField', 3, 'title', 'Jun'),
(NULL, 205, 'pjField', 1, 'title', 'Jul'),
(NULL, 205, 'pjField', 2, 'title', 'Jul'),
(NULL, 205, 'pjField', 3, 'title', 'Jul'),
(NULL, 206, 'pjField', 1, 'title', 'Aug'),
(NULL, 206, 'pjField', 2, 'title', 'Aug'),
(NULL, 206, 'pjField', 3, 'title', 'Aug'),
(NULL, 207, 'pjField', 1, 'title', 'Sep'),
(NULL, 207, 'pjField', 2, 'title', 'Sep'),
(NULL, 207, 'pjField', 3, 'title', 'Sep'),
(NULL, 208, 'pjField', 1, 'title', 'You are not loged in.'),
(NULL, 208, 'pjField', 2, 'title', 'You are not loged in.'),
(NULL, 208, 'pjField', 3, 'title', 'You are not loged in.'),
(NULL, 209, 'pjField', 1, 'title', 'Your hosting account does not allow uploading such a large image.'),
(NULL, 209, 'pjField', 2, 'title', 'Your hosting account does not allow uploading such a large image.'),
(NULL, 209, 'pjField', 3, 'title', 'Your hosting account does not allow uploading such a large image.'),
(NULL, 210, 'pjField', 1, 'title', 'Access denied. You have not requisite rights to.'),
(NULL, 210, 'pjField', 2, 'title', 'Access denied. You have not requisite rights to.'),
(NULL, 210, 'pjField', 3, 'title', 'Access denied. You have not requisite rights to.'),
(NULL, 211, 'pjField', 1, 'title', 'Empty resultset.'),
(NULL, 211, 'pjField', 2, 'title', 'Empty resultset.'),
(NULL, 211, 'pjField', 3, 'title', 'Empty resultset.'),
(NULL, 212, 'pjField', 1, 'title', 'The operation is not allowed in demo mode.'),
(NULL, 212, 'pjField', 2, 'title', 'The operation is not allowed in demo mode.'),
(NULL, 212, 'pjField', 3, 'title', 'The operation is not allowed in demo mode.'),
(NULL, 213, 'pjField', 1, 'title', 'No property for the reservation found'),
(NULL, 213, 'pjField', 2, 'title', 'No property for the reservation found'),
(NULL, 213, 'pjField', 3, 'title', 'No property for the reservation found'),
(NULL, 214, 'pjField', 1, 'title', 'No reservation found'),
(NULL, 214, 'pjField', 2, 'title', 'No reservation found'),
(NULL, 214, 'pjField', 3, 'title', 'No reservation found'),
(NULL, 215, 'pjField', 1, 'title', 'No permisions to edit the reservation'),
(NULL, 215, 'pjField', 2, 'title', 'No permisions to edit the reservation'),
(NULL, 215, 'pjField', 3, 'title', 'No permisions to edit the reservation'),
(NULL, 216, 'pjField', 1, 'title', 'No permisions to edit the property'),
(NULL, 216, 'pjField', 2, 'title', 'No permisions to edit the property'),
(NULL, 216, 'pjField', 3, 'title', 'No permisions to edit the property'),
(NULL, 217, 'pjField', 1, 'title', 'E-Mail address already exist'),
(NULL, 217, 'pjField', 2, 'title', 'E-Mail address already exist'),
(NULL, 217, 'pjField', 3, 'title', 'E-Mail address already exist'),
(NULL, 218, 'pjField', 1, 'title', 'Your registration was successfull. Your account needs to be approved.'),
(NULL, 218, 'pjField', 2, 'title', 'Your registration was successfull. Your account needs to be approved.'),
(NULL, 218, 'pjField', 3, 'title', 'Your registration was successfull. Your account needs to be approved.'),
(NULL, 219, 'pjField', 1, 'title', 'Your registration was successfull.'),
(NULL, 219, 'pjField', 2, 'title', 'Your registration was successfull.'),
(NULL, 219, 'pjField', 3, 'title', 'Your registration was successfull.'),
(NULL, 220, 'pjField', 1, 'title', 'GMT-03:00'),
(NULL, 220, 'pjField', 2, 'title', 'GMT-03:00'),
(NULL, 220, 'pjField', 3, 'title', 'GMT-03:00'),
(NULL, 221, 'pjField', 1, 'title', 'GMT-04:00'),
(NULL, 221, 'pjField', 2, 'title', 'GMT-04:00'),
(NULL, 221, 'pjField', 3, 'title', 'GMT-04:00'),
(NULL, 222, 'pjField', 1, 'title', 'GMT-05:00'),
(NULL, 222, 'pjField', 2, 'title', 'GMT-05:00'),
(NULL, 222, 'pjField', 3, 'title', 'GMT-05:00'),
(NULL, 223, 'pjField', 1, 'title', 'GMT-06:00'),
(NULL, 223, 'pjField', 2, 'title', 'GMT-06:00'),
(NULL, 223, 'pjField', 3, 'title', 'GMT-06:00'),
(NULL, 224, 'pjField', 1, 'title', 'GMT-07:00'),
(NULL, 224, 'pjField', 2, 'title', 'GMT-07:00'),
(NULL, 224, 'pjField', 3, 'title', 'GMT-07:00'),
(NULL, 225, 'pjField', 1, 'title', 'GMT-08:00'),
(NULL, 225, 'pjField', 2, 'title', 'GMT-08:00'),
(NULL, 225, 'pjField', 3, 'title', 'GMT-08:00'),
(NULL, 226, 'pjField', 1, 'title', 'GMT-09:00'),
(NULL, 226, 'pjField', 2, 'title', 'GMT-09:00'),
(NULL, 226, 'pjField', 3, 'title', 'GMT-09:00'),
(NULL, 227, 'pjField', 1, 'title', 'GMT-01:00'),
(NULL, 227, 'pjField', 2, 'title', 'GMT-01:00'),
(NULL, 227, 'pjField', 3, 'title', 'GMT-01:00'),
(NULL, 228, 'pjField', 1, 'title', 'GMT-10:00'),
(NULL, 228, 'pjField', 2, 'title', 'GMT-10:00'),
(NULL, 228, 'pjField', 3, 'title', 'GMT-10:00'),
(NULL, 229, 'pjField', 1, 'title', 'GMT-11:00'),
(NULL, 229, 'pjField', 2, 'title', 'GMT-11:00'),
(NULL, 229, 'pjField', 3, 'title', 'GMT-11:00'),
(NULL, 230, 'pjField', 1, 'title', 'GMT-12:00'),
(NULL, 230, 'pjField', 2, 'title', 'GMT-12:00'),
(NULL, 230, 'pjField', 3, 'title', 'GMT-12:00'),
(NULL, 231, 'pjField', 1, 'title', 'GMT-02:00'),
(NULL, 231, 'pjField', 2, 'title', 'GMT-02:00'),
(NULL, 231, 'pjField', 3, 'title', 'GMT-02:00'),
(NULL, 232, 'pjField', 1, 'title', 'GMT'),
(NULL, 232, 'pjField', 2, 'title', 'GMT'),
(NULL, 232, 'pjField', 3, 'title', 'GMT'),
(NULL, 233, 'pjField', 1, 'title', 'GMT+03:00'),
(NULL, 233, 'pjField', 2, 'title', 'GMT+03:00'),
(NULL, 233, 'pjField', 3, 'title', 'GMT+03:00'),
(NULL, 234, 'pjField', 1, 'title', 'GMT+04:00'),
(NULL, 234, 'pjField', 2, 'title', 'GMT+04:00'),
(NULL, 234, 'pjField', 3, 'title', 'GMT+04:00'),
(NULL, 235, 'pjField', 1, 'title', 'GMT+05:00'),
(NULL, 235, 'pjField', 2, 'title', 'GMT+05:00'),
(NULL, 235, 'pjField', 3, 'title', 'GMT+05:00'),
(NULL, 236, 'pjField', 1, 'title', 'GMT+06:00'),
(NULL, 236, 'pjField', 2, 'title', 'GMT+06:00'),
(NULL, 236, 'pjField', 3, 'title', 'GMT+06:00'),
(NULL, 237, 'pjField', 1, 'title', 'GMT+07:00'),
(NULL, 237, 'pjField', 2, 'title', 'GMT+07:00'),
(NULL, 237, 'pjField', 3, 'title', 'GMT+07:00'),
(NULL, 238, 'pjField', 1, 'title', 'GMT+08:00'),
(NULL, 238, 'pjField', 2, 'title', 'GMT+08:00'),
(NULL, 238, 'pjField', 3, 'title', 'GMT+08:00'),
(NULL, 239, 'pjField', 1, 'title', 'GMT+09:00'),
(NULL, 239, 'pjField', 2, 'title', 'GMT+09:00'),
(NULL, 239, 'pjField', 3, 'title', 'GMT+09:00'),
(NULL, 240, 'pjField', 1, 'title', 'GMT+01:00'),
(NULL, 240, 'pjField', 2, 'title', 'GMT+01:00'),
(NULL, 240, 'pjField', 3, 'title', 'GMT+01:00'),
(NULL, 241, 'pjField', 1, 'title', 'GMT+10:00'),
(NULL, 241, 'pjField', 2, 'title', 'GMT+10:00'),
(NULL, 241, 'pjField', 3, 'title', 'GMT+10:00'),
(NULL, 242, 'pjField', 1, 'title', 'GMT+11:00'),
(NULL, 242, 'pjField', 2, 'title', 'GMT+11:00'),
(NULL, 242, 'pjField', 3, 'title', 'GMT+11:00'),
(NULL, 243, 'pjField', 1, 'title', 'GMT+12:00'),
(NULL, 243, 'pjField', 2, 'title', 'GMT+12:00'),
(NULL, 243, 'pjField', 3, 'title', 'GMT+12:00'),
(NULL, 244, 'pjField', 1, 'title', 'GMT+13:00'),
(NULL, 244, 'pjField', 2, 'title', 'GMT+13:00'),
(NULL, 244, 'pjField', 3, 'title', 'GMT+13:00'),
(NULL, 245, 'pjField', 1, 'title', 'GMT+02:00'),
(NULL, 245, 'pjField', 2, 'title', 'GMT+02:00'),
(NULL, 245, 'pjField', 3, 'title', 'GMT+02:00'),
(NULL, 246, 'pjField', 1, 'title', 'Inactive'),
(NULL, 246, 'pjField', 2, 'title', 'Inactive'),
(NULL, 246, 'pjField', 3, 'title', 'Inactive'),
(NULL, 247, 'pjField', 1, 'title', 'Active'),
(NULL, 247, 'pjField', 2, 'title', 'Active'),
(NULL, 247, 'pjField', 3, 'title', 'Active'),
(NULL, 248, 'pjField', 1, 'title', 'No'),
(NULL, 248, 'pjField', 2, 'title', 'No'),
(NULL, 248, 'pjField', 3, 'title', 'No'),
(NULL, 249, 'pjField', 1, 'title', 'Yes'),
(NULL, 249, 'pjField', 2, 'title', 'Yes'),
(NULL, 249, 'pjField', 3, 'title', 'Yes'),
(NULL, 274, 'pjField', 1, 'title', 'Calendar'),
(NULL, 274, 'pjField', 2, 'title', 'Calendar'),
(NULL, 274, 'pjField', 3, 'title', 'Calendar'),
(NULL, 275, 'pjField', 1, 'title', 'Events'),
(NULL, 275, 'pjField', 2, 'title', 'Events'),
(NULL, 275, 'pjField', 3, 'title', 'Events'),
(NULL, 276, 'pjField', 1, 'title', 'Categories'),
(NULL, 276, 'pjField', 2, 'title', 'Categories'),
(NULL, 276, 'pjField', 3, 'title', 'Categories'),
(NULL, 277, 'pjField', 1, 'title', 'Add category'),
(NULL, 277, 'pjField', 2, 'title', 'Add category'),
(NULL, 277, 'pjField', 3, 'title', 'Add category'),
(NULL, 278, 'pjField', 1, 'title', 'Category'),
(NULL, 278, 'pjField', 2, 'title', 'Category'),
(NULL, 278, 'pjField', 3, 'title', 'Category'),
(NULL, 279, 'pjField', 1, 'title', 'Category updated!'),
(NULL, 279, 'pjField', 2, 'title', 'Category updated!'),
(NULL, 279, 'pjField', 3, 'title', 'Category updated!'),
(NULL, 280, 'pjField', 1, 'title', 'Category added!'),
(NULL, 280, 'pjField', 2, 'title', 'Category added!'),
(NULL, 280, 'pjField', 3, 'title', 'Category added!'),
(NULL, 281, 'pjField', 2, 'title', 'Category failed to add.'),
(NULL, 281, 'pjField', 3, 'title', 'Category failed to add.'),
(NULL, 281, 'pjField', 1, 'title', 'Category failed to add.'),
(NULL, 282, 'pjField', 1, 'title', 'Category not found.'),
(NULL, 282, 'pjField', 2, 'title', 'Category not found.'),
(NULL, 282, 'pjField', 3, 'title', 'Category not found.'),
(NULL, 283, 'pjField', 1, 'title', 'All the changes made to the category have been saved.'),
(NULL, 283, 'pjField', 2, 'title', 'All the changes made to the category have been saved.'),
(NULL, 283, 'pjField', 3, 'title', 'All the changes made to the category have been saved.'),
(NULL, 284, 'pjField', 1, 'title', 'All the changes made to the category have been saved.'),
(NULL, 284, 'pjField', 2, 'title', 'All the changes made to the category have been saved.'),
(NULL, 284, 'pjField', 3, 'title', 'All the changes made to the category have been saved.'),
(NULL, 285, 'pjField', 1, 'title', 'We are sorry, but the category has not been added.'),
(NULL, 285, 'pjField', 2, 'title', 'We are sorry, but the category has not been added.'),
(NULL, 285, 'pjField', 3, 'title', 'We are sorry, but the category has not been added.'),
(NULL, 286, 'pjField', 1, 'title', 'Category your looking for is missing.'),
(NULL, 286, 'pjField', 2, 'title', 'Category your looking for is missing.'),
(NULL, 286, 'pjField', 3, 'title', 'Category your looking for is missing.'),
(NULL, 287, 'pjField', 1, 'title', 'Update category'),
(NULL, 287, 'pjField', 2, 'title', 'Update category'),
(NULL, 287, 'pjField', 3, 'title', 'Update category'),
(NULL, 288, 'pjField', 1, 'title', 'Event updated!'),
(NULL, 288, 'pjField', 2, 'title', 'Event updated!'),
(NULL, 288, 'pjField', 3, 'title', 'Event updated!'),
(NULL, 289, 'pjField', 1, 'title', 'Event added!'),
(NULL, 289, 'pjField', 2, 'title', 'Event added!'),
(NULL, 289, 'pjField', 3, 'title', 'Event added!'),
(NULL, 290, 'pjField', 1, 'title', 'Event failed to add.'),
(NULL, 290, 'pjField', 2, 'title', 'Event failed to add.'),
(NULL, 290, 'pjField', 3, 'title', 'Event failed to add.'),
(NULL, 291, 'pjField', 1, 'title', 'Event not found.'),
(NULL, 291, 'pjField', 2, 'title', 'Event not found.'),
(NULL, 291, 'pjField', 3, 'title', 'Event not found.'),
(NULL, 292, 'pjField', 1, 'title', 'All the changes made to the event have been saved.'),
(NULL, 292, 'pjField', 2, 'title', 'All the changes made to the event have been saved.'),
(NULL, 292, 'pjField', 3, 'title', 'All the changes made to the event have been saved.'),
(NULL, 293, 'pjField', 1, 'title', 'All the changes made to the event have been saved.'),
(NULL, 293, 'pjField', 2, 'title', 'All the changes made to the event have been saved.'),
(NULL, 293, 'pjField', 3, 'title', 'All the changes made to the event have been saved.'),
(NULL, 294, 'pjField', 1, 'title', 'We are sorry, but the event has not been added.'),
(NULL, 294, 'pjField', 2, 'title', 'We are sorry, but the event has not been added.'),
(NULL, 294, 'pjField', 3, 'title', 'We are sorry, but the event has not been added.'),
(NULL, 295, 'pjField', 1, 'title', 'Even your are looking for is missing.'),
(NULL, 295, 'pjField', 2, 'title', 'Even your are looking for is missing.'),
(NULL, 295, 'pjField', 3, 'title', 'Even your are looking for is missing.'),
(NULL, 296, 'pjField', 1, 'title', 'Add event'),
(NULL, 296, 'pjField', 2, 'title', 'Add event'),
(NULL, 296, 'pjField', 3, 'title', 'Add event'),
(NULL, 297, 'pjField', 1, 'title', 'Date'),
(NULL, 297, 'pjField', 2, 'title', 'Date'),
(NULL, 297, 'pjField', 3, 'title', 'Date'),
(NULL, 298, 'pjField', 1, 'title', 'Time'),
(NULL, 298, 'pjField', 2, 'title', 'Time'),
(NULL, 298, 'pjField', 3, 'title', 'Time'),
(NULL, 299, 'pjField', 1, 'title', 'Title'),
(NULL, 299, 'pjField', 2, 'title', 'Title'),
(NULL, 299, 'pjField', 3, 'title', 'Title'),
(NULL, 300, 'pjField', 1, 'title', 'End time'),
(NULL, 300, 'pjField', 2, 'title', 'End time'),
(NULL, 300, 'pjField', 3, 'title', 'End time'),
(NULL, 301, 'pjField', 1, 'title', 'Start time'),
(NULL, 301, 'pjField', 2, 'title', 'Start time'),
(NULL, 301, 'pjField', 3, 'title', 'Start time'),
(NULL, 326, 'pjField', 1, 'title', 'Time format'),
(NULL, 326, 'pjField', 2, 'title', 'Time format'),
(NULL, 326, 'pjField', 3, 'title', 'Time format'),
(NULL, 327, 'pjField', 1, 'title', 'Layout'),
(NULL, 327, 'pjField', 2, 'title', 'Layout'),
(NULL, 327, 'pjField', 3, 'title', 'Layout'),
(NULL, 328, 'pjField', 1, 'title', 'Enable categories'),
(NULL, 328, 'pjField', 2, 'title', 'Enable categories'),
(NULL, 328, 'pjField', 3, 'title', 'Enable categories'),
(NULL, 329, 'pjField', 1, 'title', 'Enable monthly view'),
(NULL, 329, 'pjField', 2, 'title', 'Enable monthly view'),
(NULL, 329, 'pjField', 3, 'title', 'Enable monthly view'),
(NULL, 330, 'pjField', 1, 'title', 'Enable list view'),
(NULL, 330, 'pjField', 2, 'title', 'Enable list view'),
(NULL, 330, 'pjField', 3, 'title', 'Enable list view'),
(NULL, 331, 'pjField', 1, 'title', 'Default view'),
(NULL, 331, 'pjField', 2, 'title', 'Default view'),
(NULL, 331, 'pjField', 3, 'title', 'Default view'),
(NULL, 332, 'pjField', 1, 'title', 'Description'),
(NULL, 332, 'pjField', 2, 'title', 'Description'),
(NULL, 332, 'pjField', 3, 'title', 'Description'),
(NULL, 333, 'pjField', 1, 'title', 'Repeat'),
(NULL, 333, 'pjField', 2, 'title', 'Repeat'),
(NULL, 333, 'pjField', 3, 'title', 'Repeat'),
(NULL, 334, 'pjField', 1, 'title', 'Daily'),
(NULL, 334, 'pjField', 2, 'title', 'Daily'),
(NULL, 334, 'pjField', 3, 'title', 'Daily'),
(NULL, 335, 'pjField', 1, 'title', 'Weekly'),
(NULL, 335, 'pjField', 2, 'title', 'Weekly'),
(NULL, 335, 'pjField', 3, 'title', 'Weekly'),
(NULL, 336, 'pjField', 1, 'title', 'Monthly'),
(NULL, 336, 'pjField', 2, 'title', 'Monthly'),
(NULL, 336, 'pjField', 3, 'title', 'Monthly'),
(NULL, 337, 'pjField', 1, 'title', 'Quarterly'),
(NULL, 337, 'pjField', 2, 'title', 'Quarterly'),
(NULL, 337, 'pjField', 3, 'title', 'Quarterly'),
(NULL, 338, 'pjField', 1, 'title', 'Yearly'),
(NULL, 338, 'pjField', 2, 'title', 'Yearly'),
(NULL, 338, 'pjField', 3, 'title', 'Yearly'),
(NULL, 339, 'pjField', 1, 'title', 'Custom'),
(NULL, 339, 'pjField', 2, 'title', 'Custom'),
(NULL, 339, 'pjField', 3, 'title', 'Custom'),
(NULL, 340, 'pjField', 1, 'title', 'None'),
(NULL, 340, 'pjField', 2, 'title', 'None'),
(NULL, 340, 'pjField', 3, 'title', 'None'),
(NULL, 341, 'pjField', 1, 'title', 'End recurring on'),
(NULL, 341, 'pjField', 2, 'title', 'End recurring on'),
(NULL, 341, 'pjField', 3, 'title', 'End recurring on'),
(NULL, 342, 'pjField', 1, 'title', 'Or repeat'),
(NULL, 342, 'pjField', 2, 'title', 'Or repeat'),
(NULL, 342, 'pjField', 3, 'title', 'Or repeat'),
(NULL, 343, 'pjField', 1, 'title', 'times'),
(NULL, 343, 'pjField', 2, 'title', 'times'),
(NULL, 343, 'pjField', 3, 'title', 'times'),
(NULL, 344, 'pjField', 1, 'title', 'each'),
(NULL, 344, 'pjField', 2, 'title', 'each'),
(NULL, 344, 'pjField', 3, 'title', 'each'),
(NULL, 346, 'pjField', 1, 'title', 'Event will be repeated daily'),
(NULL, 346, 'pjField', 2, 'title', 'Event will be repeated daily'),
(NULL, 346, 'pjField', 3, 'title', 'Event will be repeated daily'),
(NULL, 347, 'pjField', 1, 'title', 'Event will be repeated weekly'),
(NULL, 347, 'pjField', 2, 'title', 'Event will be repeated weekly'),
(NULL, 347, 'pjField', 3, 'title', 'Event will be repeated weekly'),
(NULL, 348, 'pjField', 1, 'title', 'Event will be repeated quarterly'),
(NULL, 348, 'pjField', 2, 'title', 'Event will be repeated quarterly'),
(NULL, 348, 'pjField', 3, 'title', 'Event will be repeated quarterly'),
(NULL, 349, 'pjField', 1, 'title', 'Event will be repeated yearly'),
(NULL, 349, 'pjField', 2, 'title', 'Event will be repeated yearly'),
(NULL, 349, 'pjField', 3, 'title', 'Event will be repeated yearly'),
(NULL, 350, 'pjField', 1, 'title', 'on'),
(NULL, 350, 'pjField', 2, 'title', 'on'),
(NULL, 350, 'pjField', 3, 'title', 'on'),
(NULL, 351, 'pjField', 1, 'title', 'of the month'),
(NULL, 351, 'pjField', 2, 'title', 'of the month'),
(NULL, 351, 'pjField', 3, 'title', 'of the month'),
(NULL, 352, 'pjField', 1, 'title', 'Or each'),
(NULL, 352, 'pjField', 2, 'title', 'Or each'),
(NULL, 352, 'pjField', 3, 'title', 'Or each'),
(NULL, 353, 'pjField', 1, 'title', 'First'),
(NULL, 353, 'pjField', 2, 'title', 'First'),
(NULL, 353, 'pjField', 3, 'title', 'First'),
(NULL, 354, 'pjField', 1, 'title', 'Second'),
(NULL, 354, 'pjField', 2, 'title', 'Second'),
(NULL, 354, 'pjField', 3, 'title', 'Second'),
(NULL, 355, 'pjField', 1, 'title', 'Third'),
(NULL, 355, 'pjField', 2, 'title', 'Third'),
(NULL, 355, 'pjField', 3, 'title', 'Third'),
(NULL, 356, 'pjField', 1, 'title', 'Fourth'),
(NULL, 356, 'pjField', 2, 'title', 'Fourth'),
(NULL, 356, 'pjField', 3, 'title', 'Fourth'),
(NULL, 357, 'pjField', 1, 'title', '--'),
(NULL, 357, 'pjField', 2, 'title', '--'),
(NULL, 357, 'pjField', 3, 'title', '--'),
(NULL, 358, 'pjField', 1, 'title', '1st'),
(NULL, 358, 'pjField', 2, 'title', '1st'),
(NULL, 358, 'pjField', 3, 'title', '1st'),
(NULL, 359, 'pjField', 1, 'title', '2nd'),
(NULL, 359, 'pjField', 2, 'title', '2nd'),
(NULL, 359, 'pjField', 3, 'title', '2nd'),
(NULL, 360, 'pjField', 1, 'title', '3rd'),
(NULL, 360, 'pjField', 2, 'title', '3rd'),
(NULL, 360, 'pjField', 3, 'title', '3rd'),
(NULL, 361, 'pjField', 1, 'title', '4th'),
(NULL, 361, 'pjField', 2, 'title', '4th'),
(NULL, 361, 'pjField', 3, 'title', '4th'),
(NULL, 362, 'pjField', 1, 'title', '5th'),
(NULL, 362, 'pjField', 2, 'title', '5th'),
(NULL, 362, 'pjField', 3, 'title', '5th'),
(NULL, 363, 'pjField', 1, 'title', '6th'),
(NULL, 363, 'pjField', 2, 'title', '6th'),
(NULL, 363, 'pjField', 3, 'title', '6th'),
(NULL, 364, 'pjField', 1, 'title', '8th'),
(NULL, 364, 'pjField', 2, 'title', '8th'),
(NULL, 364, 'pjField', 3, 'title', '8th'),
(NULL, 365, 'pjField', 1, 'title', '9th'),
(NULL, 365, 'pjField', 2, 'title', '9th'),
(NULL, 365, 'pjField', 3, 'title', '9th'),
(NULL, 366, 'pjField', 1, 'title', '10th'),
(NULL, 366, 'pjField', 2, 'title', '10th'),
(NULL, 366, 'pjField', 3, 'title', '10th'),
(NULL, 367, 'pjField', 1, 'title', '11th'),
(NULL, 367, 'pjField', 2, 'title', '11th'),
(NULL, 367, 'pjField', 3, 'title', '11th'),
(NULL, 368, 'pjField', 1, 'title', '12th'),
(NULL, 368, 'pjField', 2, 'title', '12th'),
(NULL, 368, 'pjField', 3, 'title', '12th'),
(NULL, 369, 'pjField', 1, 'title', '13th'),
(NULL, 369, 'pjField', 2, 'title', '13th'),
(NULL, 369, 'pjField', 3, 'title', '13th'),
(NULL, 370, 'pjField', 1, 'title', '14th'),
(NULL, 370, 'pjField', 2, 'title', '14th'),
(NULL, 370, 'pjField', 3, 'title', '14th'),
(NULL, 371, 'pjField', 1, 'title', '15th'),
(NULL, 371, 'pjField', 2, 'title', '15th'),
(NULL, 371, 'pjField', 3, 'title', '15th'),
(NULL, 372, 'pjField', 1, 'title', '16th'),
(NULL, 372, 'pjField', 2, 'title', '16th'),
(NULL, 372, 'pjField', 3, 'title', '16th'),
(NULL, 373, 'pjField', 1, 'title', '17th'),
(NULL, 373, 'pjField', 2, 'title', '17th'),
(NULL, 373, 'pjField', 3, 'title', '17th'),
(NULL, 374, 'pjField', 1, 'title', '18th'),
(NULL, 374, 'pjField', 2, 'title', '18th'),
(NULL, 374, 'pjField', 3, 'title', '18th'),
(NULL, 375, 'pjField', 1, 'title', '19th'),
(NULL, 375, 'pjField', 2, 'title', '19th'),
(NULL, 375, 'pjField', 3, 'title', '19th'),
(NULL, 376, 'pjField', 1, 'title', '20th'),
(NULL, 376, 'pjField', 2, 'title', '20th'),
(NULL, 376, 'pjField', 3, 'title', '20th'),
(NULL, 377, 'pjField', 1, 'title', '21st'),
(NULL, 377, 'pjField', 2, 'title', '21st'),
(NULL, 377, 'pjField', 3, 'title', '21st'),
(NULL, 378, 'pjField', 1, 'title', '22nd'),
(NULL, 378, 'pjField', 2, 'title', '22nd'),
(NULL, 378, 'pjField', 3, 'title', '22nd'),
(NULL, 379, 'pjField', 1, 'title', '23rd'),
(NULL, 379, 'pjField', 2, 'title', '23rd'),
(NULL, 379, 'pjField', 3, 'title', '23rd'),
(NULL, 380, 'pjField', 1, 'title', '24th'),
(NULL, 380, 'pjField', 2, 'title', '24th'),
(NULL, 380, 'pjField', 3, 'title', '24th'),
(NULL, 381, 'pjField', 1, 'title', '25th'),
(NULL, 381, 'pjField', 2, 'title', '25th'),
(NULL, 381, 'pjField', 3, 'title', '25th'),
(NULL, 382, 'pjField', 1, 'title', '26th'),
(NULL, 382, 'pjField', 2, 'title', '26th'),
(NULL, 382, 'pjField', 3, 'title', '26th'),
(NULL, 383, 'pjField', 1, 'title', '27th'),
(NULL, 383, 'pjField', 2, 'title', '27th'),
(NULL, 383, 'pjField', 3, 'title', '27th'),
(NULL, 384, 'pjField', 1, 'title', '28th'),
(NULL, 384, 'pjField', 2, 'title', '28th'),
(NULL, 384, 'pjField', 3, 'title', '28th'),
(NULL, 385, 'pjField', 1, 'title', '29th'),
(NULL, 385, 'pjField', 2, 'title', '29th'),
(NULL, 385, 'pjField', 3, 'title', '29th'),
(NULL, 386, 'pjField', 1, 'title', '30th'),
(NULL, 386, 'pjField', 2, 'title', '30th'),
(NULL, 386, 'pjField', 3, 'title', '30th'),
(NULL, 387, 'pjField', 1, 'title', '31st'),
(NULL, 387, 'pjField', 2, 'title', '31st'),
(NULL, 387, 'pjField', 3, 'title', '31st'),
(NULL, 388, 'pjField', 1, 'title', 'Add time'),
(NULL, 388, 'pjField', 2, 'title', 'Add time'),
(NULL, 388, 'pjField', 3, 'title', 'Add time'),
(NULL, 389, 'pjField', 1, 'title', 'Add start time'),
(NULL, 389, 'pjField', 2, 'title', 'Add start time'),
(NULL, 389, 'pjField', 3, 'title', 'Add start time'),
(NULL, 390, 'pjField', 1, 'title', 'Add end time'),
(NULL, 390, 'pjField', 2, 'title', 'Add end time'),
(NULL, 390, 'pjField', 3, 'title', 'Add end time'),
(NULL, 391, 'pjField', 3, 'title', 'Remove time'),
(NULL, 391, 'pjField', 1, 'title', 'Remove time'),
(NULL, 391, 'pjField', 2, 'title', 'Remove time'),
(NULL, 416, 'pjField', 1, 'title', 'Update event'),
(NULL, 416, 'pjField', 2, 'title', 'Update event'),
(NULL, 416, 'pjField', 3, 'title', 'Update event'),
(NULL, 417, 'pjField', 1, 'title', 'This is recurring event. Check if you want to update all the {numevents} repeats or leave unchecked if you only want to update this current event.'),
(NULL, 417, 'pjField', 2, 'title', 'This is recurring event. Check if you want to update all the {numevents} repeats or leave unchecked if you only want to update this current event.'),
(NULL, 417, 'pjField', 3, 'title', 'This is recurring event. Check if you want to update all the {numevents} repeats or leave unchecked if you only want to update this current event.'),
(NULL, 418, 'pjField', 1, 'title', 'Choose'),
(NULL, 418, 'pjField', 2, 'title', 'Choose'),
(NULL, 418, 'pjField', 3, 'title', 'Choose'),
(NULL, 419, 'pjField', 1, 'title', 'Install'),
(NULL, 419, 'pjField', 2, 'title', 'Install'),
(NULL, 419, 'pjField', 3, 'title', 'Install'),
(NULL, 420, 'pjField', 1, 'title', 'Install'),
(NULL, 420, 'pjField', 2, 'title', 'Install'),
(NULL, 420, 'pjField', 3, 'title', 'Install'),
(NULL, 421, 'pjField', 1, 'title', 'Please follow these steps to do the installation.'),
(NULL, 421, 'pjField', 2, 'title', 'Please follow these steps to do the installation.'),
(NULL, 421, 'pjField', 3, 'title', 'Please follow these steps to do the installation.'),
(NULL, 422, 'pjField', 1, 'title', 'Step 1: (Optional) Do any customization to have your desired PHP event calendar.'),
(NULL, 422, 'pjField', 2, 'title', 'Step 1: (Optional) Do any customization to have your desired PHP event calendar.'),
(NULL, 422, 'pjField', 3, 'title', 'Step 1: (Optional) Do any customization to have your desired PHP event calendar.'),
(NULL, 423, 'pjField', 1, 'title', 'Step 2. (Required) Copy the code below and put it in your web page where you want the event calendar to appear.'),
(NULL, 423, 'pjField', 2, 'title', 'Step 2. (Required) Copy the code below and put it in your web page where you want the event calendar to appear.'),
(NULL, 423, 'pjField', 3, 'title', 'Step 2. (Required) Copy the code below and put it in your web page where you want the event calendar to appear.'),
(NULL, 424, 'pjField', 1, 'title', 'Number of events per page for list view'),
(NULL, 424, 'pjField', 2, 'title', 'Number of events per page for list view'),
(NULL, 424, 'pjField', 3, 'title', 'Number of events per page for list view'),
(NULL, 425, 'pjField', 1, 'title', 'Display events for calendar view'),
(NULL, 425, 'pjField', 2, 'title', 'Display events for calendar view'),
(NULL, 425, 'pjField', 3, 'title', 'Display events for calendar view'),
(NULL, 426, 'pjField', 1, 'title', 'View'),
(NULL, 426, 'pjField', 2, 'title', 'View'),
(NULL, 426, 'pjField', 3, 'title', 'View'),
(NULL, 427, 'pjField', 1, 'title', 'Hide view switch icons'),
(NULL, 427, 'pjField', 2, 'title', 'Hide view switch icons'),
(NULL, 427, 'pjField', 3, 'title', 'Hide view switch icons'),
(NULL, 428, 'pjField', 1, 'title', 'Hide categories'),
(NULL, 428, 'pjField', 2, 'title', 'Hide categories'),
(NULL, 428, 'pjField', 3, 'title', 'Hide categories'),
(NULL, 429, 'pjField', 1, 'title', 'CSS file'),
(NULL, 429, 'pjField', 2, 'title', 'CSS file'),
(NULL, 429, 'pjField', 3, 'title', 'CSS file'),
(NULL, 430, 'pjField', 1, 'title', 'Default'),
(NULL, 430, 'pjField', 2, 'title', 'Default'),
(NULL, 430, 'pjField', 3, 'title', 'Default'),
(NULL, 431, 'pjField', 1, 'title', 'List'),
(NULL, 431, 'pjField', 2, 'title', 'List'),
(NULL, 431, 'pjField', 3, 'title', 'List'),
(NULL, 432, 'pjField', 1, 'title', 'Calendar'),
(NULL, 432, 'pjField', 2, 'title', 'Calendar'),
(NULL, 432, 'pjField', 3, 'title', 'Calendar'),
(NULL, 433, 'pjField', 1, 'title', 'Monthly'),
(NULL, 433, 'pjField', 2, 'title', 'Monthly'),
(NULL, 433, 'pjField', 3, 'title', 'Monthly'),
(NULL, 434, 'pjField', 1, 'title', 'Preparation step: Please do any customization to have your desired PHP event calendar. '),
(NULL, 434, 'pjField', 2, 'title', 'Preparation step: Please do any customization to have your desired PHP event calendar. '),
(NULL, 434, 'pjField', 3, 'title', 'Preparation step: Please do any customization to have your desired PHP event calendar. '),
(NULL, 435, 'pjField', 1, 'title', 'Calendar view'),
(NULL, 435, 'pjField', 2, 'title', 'Calendar view'),
(NULL, 435, 'pjField', 3, 'title', 'Calendar view'),
(NULL, 436, 'pjField', 1, 'title', 'List view'),
(NULL, 436, 'pjField', 2, 'title', 'List view'),
(NULL, 436, 'pjField', 3, 'title', 'List view'),
(NULL, 437, 'pjField', 1, 'title', 'Monthly view'),
(NULL, 437, 'pjField', 2, 'title', 'Monthly view'),
(NULL, 437, 'pjField', 3, 'title', 'Monthly view'),
(NULL, 438, 'pjField', 1, 'title', '{DefaultCSS} is the default css file for the layout, but if you want you can save it under a new name, then change the textbox here and use the new file.'),
(NULL, 438, 'pjField', 2, 'title', '{DefaultCSS} is the default css file for the layout, but if you want you can save it under a new name, then change the textbox here and use the new file.'),
(NULL, 438, 'pjField', 3, 'title', '{DefaultCSS} is the default css file for the layout, but if you want you can save it under a new name, then change the textbox here and use the new file.'),
(NULL, 439, 'pjField', 1, 'title', 'Preview'),
(NULL, 439, 'pjField', 2, 'title', 'Preview'),
(NULL, 439, 'pjField', 3, 'title', 'Preview'),
(NULL, 440, 'pjField', 1, 'title', 'No event found'),
(NULL, 440, 'pjField', 2, 'title', 'No event found'),
(NULL, 440, 'pjField', 3, 'title', 'No event found'),
(NULL, 441, 'pjField', 1, 'title', 'Time'),
(NULL, 441, 'pjField', 2, 'title', 'Time'),
(NULL, 441, 'pjField', 3, 'title', 'Time'),
(NULL, 442, 'pjField', 1, 'title', 'Last login'),
(NULL, 442, 'pjField', 2, 'title', 'Last login'),
(NULL, 442, 'pjField', 3, 'title', 'Last login'),
(NULL, 443, 'pjField', 1, 'title', 'Today events'),
(NULL, 443, 'pjField', 2, 'title', 'Today events'),
(NULL, 443, 'pjField', 3, 'title', 'Today events'),
(NULL, 444, 'pjField', 1, 'title', 'Total events'),
(NULL, 444, 'pjField', 2, 'title', 'Total events'),
(NULL, 444, 'pjField', 3, 'title', 'Total events'),
(NULL, 445, 'pjField', 1, 'title', 'Upcoming events'),
(NULL, 445, 'pjField', 2, 'title', 'Upcoming events'),
(NULL, 445, 'pjField', 3, 'title', 'Upcoming events'),
(NULL, 446, 'pjField', 1, 'title', 'Users'),
(NULL, 446, 'pjField', 2, 'title', 'Users'),
(NULL, 446, 'pjField', 3, 'title', 'Users'),
(NULL, 447, 'pjField', 1, 'title', 'Layout 1'),
(NULL, 447, 'pjField', 2, 'title', 'Layout 1'),
(NULL, 447, 'pjField', 3, 'title', 'Layout 1'),
(NULL, 448, 'pjField', 1, 'title', 'Layout 2'),
(NULL, 448, 'pjField', 2, 'title', 'Layout 2'),
(NULL, 448, 'pjField', 3, 'title', 'Layout 2'),
(NULL, 449, 'pjField', 1, 'title', 'Layout 3'),
(NULL, 449, 'pjField', 2, 'title', 'Layout 3'),
(NULL, 449, 'pjField', 3, 'title', 'Layout 3'),
(NULL, 450, 'pjField', 1, 'title', 'Layout 4'),
(NULL, 450, 'pjField', 2, 'title', 'Layout 4'),
(NULL, 450, 'pjField', 3, 'title', 'Layout 4'),
(NULL, 451, 'pjField', 1, 'title', 'Layout 5'),
(NULL, 451, 'pjField', 2, 'title', 'Layout 5'),
(NULL, 451, 'pjField', 3, 'title', 'Layout 5'),
(NULL, 452, 'pjField', 1, 'title', 'Are you sure you want to delete selected record(s)?'),
(NULL, 452, 'pjField', 2, 'title', 'Are you sure you want to delete selected record(s)?'),
(NULL, 452, 'pjField', 3, 'title', 'Are you sure you want to delete selected record(s)?'),
(NULL, 453, 'pjField', 1, 'title', 'Enable tooltip'),
(NULL, 453, 'pjField', 2, 'title', 'Enable tooltip'),
(NULL, 453, 'pjField', 3, 'title', 'Enable tooltip'),
(NULL, 454, 'pjField', 1, 'title', 'Event title position'),
(NULL, 454, 'pjField', 2, 'title', 'Event title position'),
(NULL, 454, 'pjField', 3, 'title', 'Event title position'),
(NULL, 455, 'pjField', 1, 'title', '7th'),
(NULL, 455, 'pjField', 2, 'title', '7th'),
(NULL, 455, 'pjField', 3, 'title', '7th'),
(NULL, 456, 'pjField', 1, 'title', 'The end time must come after start time.'),
(NULL, 456, 'pjField', 2, 'title', 'The end time must come after start time.'),
(NULL, 456, 'pjField', 3, 'title', 'The end time must come after start time.'),
(NULL, 457, 'pjField', 1, 'title', 'Sun'),
(NULL, 457, 'pjField', 2, 'title', 'Sun'),
(NULL, 457, 'pjField', 3, 'title', 'Sun'),
(NULL, 458, 'pjField', 1, 'title', 'Mon'),
(NULL, 458, 'pjField', 2, 'title', 'Mon'),
(NULL, 458, 'pjField', 3, 'title', 'Mon'),
(NULL, 459, 'pjField', 1, 'title', 'Tue'),
(NULL, 459, 'pjField', 2, 'title', 'Tue'),
(NULL, 459, 'pjField', 3, 'title', 'Tue'),
(NULL, 460, 'pjField', 1, 'title', 'Wed'),
(NULL, 460, 'pjField', 2, 'title', 'Wed'),
(NULL, 460, 'pjField', 3, 'title', 'Wed'),
(NULL, 461, 'pjField', 1, 'title', 'Thu'),
(NULL, 461, 'pjField', 2, 'title', 'Thu'),
(NULL, 461, 'pjField', 3, 'title', 'Thu'),
(NULL, 462, 'pjField', 1, 'title', 'Fri'),
(NULL, 462, 'pjField', 2, 'title', 'Fri'),
(NULL, 462, 'pjField', 3, 'title', 'Fri'),
(NULL, 463, 'pjField', 1, 'title', 'Sat'),
(NULL, 463, 'pjField', 2, 'title', 'Sat'),
(NULL, 463, 'pjField', 3, 'title', 'Sat'),
(NULL, 464, 'pjField', 1, 'title', 'Category name was already used.'),
(NULL, 464, 'pjField', 2, 'title', 'Category name was already used.'),
(NULL, 464, 'pjField', 3, 'title', 'Category name was already used.');

INSERT INTO `phpeventcalendar_options` (`foreign_id`, `key`, `tab_id`, `value`, `label`, `type`, `order`, `is_visible`, `style`) VALUES
(1, 'o_date_format', 1, 'd.m.Y|m.d.Y|Y.m.d|j.n.Y|n.j.Y|Y.n.j|d/m/Y|m/d/Y|Y/m/d|j/n/Y|n/j/Y|Y/n/j|d-m-Y|m-d-Y|Y-m-d|j-n-Y|n-j-Y|Y-n-j::d-m-Y', 'd.m.Y (25.09.2012)|m.d.Y (09.25.2012)|Y.m.d (2012.09.25)|j.n.Y (25.9.2012)|n.j.Y (9.25.2012)|Y.n.j (2012.9.25)|d/m/Y (25/09/2012)|m/d/Y (09/25/2012)|Y/m/d (2012/09/25)|j/n/Y (25/9/2012)|n/j/Y (9/25/2012)|Y/n/j (2012/9/25)|d-m-Y (25-09-2012)|m-d-Y (09-25-2012)|Y-m-d (2012-09-25)|j-n-Y (25-9-2012)|n-j-Y (9-25-2012)|Y-n-j (2012-9-25)', 'enum', 1, 1, NULL),
(1, 'o_time_format', 1, 'H:i|G:i|h:i|h:i a|h:i A|g:i|g:i a|g:i A::H:i', 'H:i (09:45)|G:i (9:45)|h:i (09:45)|h:i a (09:45 am)|h:i A (09:45 AM)|g:i (9:45)|g:i a (9:45 am)|g:i A (9:45 AM)', 'enum', 2, 1, NULL),
(1, 'o_timezone', 1, '-43200|-39600|-36000|-32400|-28800|-25200|-21600|-18000|-14400|-10800|-7200|-3600|0|3600|7200|10800|14400|18000|21600|25200|28800|32400|36000|39600|43200|46800::0', 'GMT-12:00|GMT-11:00|GMT-10:00|GMT-09:00|GMT-08:00|GMT-07:00|GMT-06:00|GMT-05:00|GMT-04:00|GMT-03:00|GMT-02:00|GMT-01:00|GMT|GMT+01:00|GMT+02:00|GMT+03:00|GMT+04:00|GMT+05:00|GMT+06:00|GMT+07:00|GMT+08:00|GMT+09:00|GMT+10:00|GMT+11:00|GMT+12:00|GMT+13:00', 'enum', 3, 1, NULL),
(1, 'o_week_start', 1, '0|1|2|3|4|5|6::1', 'Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday', 'enum', 4, 1, NULL),
(1, 'o_enable_categories', 1, 'Yes|No::Yes', NULL, 'enum', 5, 1, NULL),
(1, 'o_enable_monthly_view', 1, 'Yes|No::Yes', NULL, 'enum', 6, 1, NULL),
(1, 'o_enable_list_view', 1, 'Yes|No::Yes', NULL, 'enum', 7, 1, NULL),
(1, 'o_events_per_page', 1, '5', NULL, 'int', 8, 1, NULL),
(1, 'o_display_events', 1, 'below|replace::below', 'Below calendar|Replace calendar', 'enum', 9, 1, NULL),
(1, 'o_event_title_position', 1, 'tooltip|datecell|hidden::tooltip', 'Tooltip|In date cell|Hidden', 'enum', 10, 1, NULL),
(1, 'o_multi_lang', 99, '1|0::0', 'Yes|No', 'enum', NULL, 1, NULL);

INSERT INTO `phpeventcalendar_roles` (`id`, `role`, `status`) VALUES
(1, 'admin', 'T'),
(2, 'editor', 'T');